- src/datachain/lib/file.py
- tests/func/test_datachain.py
Fixes #163.
I have also changed the order of some fields in `File`.
> DataChain.from_storage: add last_modified and is_latest to the columns

- .github/workflows/tests.yml
- tests/conftest.py
> ci: run s3 tests on Windows, be more careful while skipping

- src/datachain/cli.py
Makes it easier for debugging (I am lazy to open `sqlite3`), and the schema output is much nicer compared to `json`.
```console
$ datachain show lib --schema
sys__id            sys__rand file__source                                       file__parent           file__name  file__size file__version             file__etag  file__is_latest       file__last_modified file__location file__vtype
0        1    16214029120339813     file:///  Users/user/Projects/iterative/datachain/src/...      meta_formats.py        6920                0x1.9a7cf985506bdp+30                1 1970-01-01 00:00:00+00:00           None
1        2  8275000329518315177     file:///  Users/user/Projects/iterative/datachain/src/...        webdataset.py        8295                0x1.9a6443a179d88p+30                1 …
```
> show: add --schema

- src/datachain/lib/convert/values_to_tuples.py
- tests/unit/lib/test_datachain.py
Just a small fix with more unit tests
> from_values with array of arrays

- docs/index.md
> remove collect_one from example

- docs/index.md
> remove reference to missing notebook

- examples/get_started/json-csv-reader.py
- src/datachain/lib/dc.py
- src/datachain/lib/meta_formats.py
Minor improvements to JSON validation code:
1. Offending row numbers now reported to pinpoint data errors in JSON arrays and JSON lines
2. Methods show_json*_schema() were renamed to print_json*_schema() for consistency
3. examples modified to reflect these changes
> validation error handling improved

- examples/computer_vision/iptc_exif_xmp_lib.py
- examples/computer_vision/openimage-detect.py
- examples/get_started/json-csv-reader.py
- examples/get_started/torch-loader.py
- examples/multimodal/wds.py
- examples/multimodal/wds_filtered.py
splitting example updates out of #199
> improve efficiency of examples

- src/datachain/lib/dc.py
- tests/unit/lib/test_datachain.py
closes https://github.com/iterative/dvcx/issues/1555
> rename DataChain's create_empty to from_records

- src/datachain/lib/dc.py
> Fix typo in `filter` method docstings

- src/datachain/lib/dc.py
Fix: from_parquet() return type #231
> use D replace "DataChain"

- README.rst
Fix: Readme uses outdated mistral lib #268
> update readme about Mistral

- README.rst
Next step: improve code examples
> readme update 2

- src/datachain/sql/functions/string.py
- src/datachain/sql/sqlite/base.py
- tests/unit/sql/test_string.py
Adds `regexp_replace()` function. 
Closes #303
> add_regexp_replace

- tests/unit/lib/test_datachain.py
test failed for Clickhouse randomly here: https://github.com/iterative/datachain/actions/runs/10463877840/job/28976586712
> fix test_union_different_column_order

- src/datachain/lib/dc.py
- tests/func/test_datachain.py
Fix: mutate() cannot modify an existing column 
Closes #297
> Mutate cannot modify existing column

- src/datachain/query/dataset.py
- src/datachain/query/session.py
Small cleanup to avoid creating hardcoded prefixes.
> session: add get_temp_prefix

- examples/multimodal/wds_filtered.py
No longer required after https://github.com/iterative/datachain/pull/348
> remove LaionMeta model store registration from wds example

- examples/llm_and_nlp/unstructured-text.py
Missed in https://github.com/iterative/datachain/pull/332
> unstructured example - remove misleading install instructions

- tests/test_query_e2e.py
Failures:
- https://github.com/iterative/datachain/actions/runs/10675571652/job/29587760694
- https://github.com/iterative/datachain/actions/runs/10675771784/job/29588290330
- https://github.com/iterative/datachain/actions/runs/10672383149
- https://github.com/iterative/datachain/actions/runs/10672383149/attempts/2
- https://github.com/iterative/datachain/actions/runs/10672383149/attempts/1
> increase timeout of e2e test

- pyproject.toml
- src/datachain/lib/hf.py
- tests/unit/lib/test_datachain.py
Fixing the breakage in the pipeline demonstrated [here](https://github.com/iterative/datachain/actions/runs/10713276424)
> fix issues with new version of huggingface datasets package

- pyproject.toml
2.9.0 has breaking changes that are beyond me solving in the next 20 minutes
Failures: 
- https://github.com/iterative/datachain/actions/runs/10726012473
- https://github.com/iterative/datachain/actions/runs/10724648636
> pin pydantic < 2.9

- src/datachain/lib/meta_formats.py
- tests/func/test_meta_formats.py
See https://github.com/pydantic/pydantic/pull/10113#issuecomment-2337337368.
> read_schema: avoid passing locals to exec while executing pydantic models

- src/datachain/asyn.py
- src/datachain/client/azure.py
- src/datachain/client/fsspec.py
- src/datachain/client/gcs.py
- src/datachain/client/hf.py
- src/datachain/client/local.py
- src/datachain/client/s3.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/listing.py
- src/datachain/listing.py
- src/datachain/node.py
- tests/data.py
- tests/func/test_catalog.py
- tests/func/test_pull.py
- tests/unit/test_listing.py
Also refactors `warehouse.prepare_entries()`, see [companion PR](https://github.com/iterative/studio/pull/10645).
Part of #36.
> Remove Entry class and use File instead

- src/datachain/lib/signal_schema.py
- tests/unit/lib/test_signal_schema.py
> Set stream for nested file signals

- src/datachain/query/dataset.py
- src/datachain/query/dispatch.py
- src/datachain/query/udf.py
> Remove obsolete UDF code

- mkdocs.yml
- overrides/main.html
- add reo.dev setup for datachain docs
- added DataChain website link in nav (closes https://github.com/iterative/datachain.ai/issues/226)
> chore: add reo.dev setup

- src/datachain/data_storage/metastore.py
- src/datachain/data_storage/warehouse.py
- src/datachain/dataset.py
- tests/conftest.py
- tests/func/test_catalog.py
- tests/func/test_pull.py
- tests/unit/test_warehouse.py
This PR removes the legacy "shadow" attribute from the codebase.
companion PR: https://github.com/iterative/studio/pull/10738
> remove legacy shadow attribute

- src/datachain/lib/udf.py
Aggregator and BatchMapper are doing the same thing here, so can use the same implementation. Part of the refactoring for #40.
> Remove code duplication: UDFBase._parse_grouped_rows()

- tests/scripts/feature_class_exception.py
https://github.com/iterative/datachain/pull/494#discussion_r1791039347
> Simplify test for atomicity

- src/datachain/lib/dc.py
- src/datachain/lib/signal_schema.py
- src/datachain/query/dataset.py
- tests/func/test_datachain.py
> datachain: support mutating existing column

- .github/workflows/tests-studio.yml
> ci: fix studio tests' run

- overrides/main.html
- closes https://github.com/iterative/datachain/issues/552
> feat: setup plausible

- .github/workflows/tests-studio.yml
Following the migration in https://github.com/iterative/studio/pull/10873
> Make main default branch for CI action

- README.rst
Minor syntax update to add missing preposition "from"
> Update README.rst, added missing preposition.

- src/datachain/lib/dc.py
- src/datachain/lib/meta_formats.py
- src/datachain/lib/signal_schema.py
Fix types a bit as part of the https://github.com/iterative/datachain/pull/581 (to keep that PR focused)
> fix(dc): collect function return types

- pyproject.toml
Old version of Azurite no longer works.
> update pytest-servers to 0.5.8

- src/datachain/lib/dc.py
- tests/unit/lib/test_datachain.py
Fixes #481 
Works like this:
```
dc = DataChain.from_dataset("raw_text").explode("json").save("exploded")
```
where `json` column (`str` type) that contains JSON.
It's part of the [#10596](https://github.com/iterative/studio/issues/10596). And was also requested by @tibor-mach for a customer scenarios.
> feat(dc): add explode function

- tests/unit/lib/test_datachain.py
Followup. I didn't notice a comment by @dreadatour  here - https://github.com/iterative/datachain/pull/607#discussion_r1855056919
> fix(tests): minor fix in comment

- src/datachain/lib/dc.py
> docs: document prefetch

- src/datachain/data_storage/metastore.py
> remove unused _parse_datasets method from abstract db metastore

- src/datachain/func/__init__.py
- src/datachain/func/func.py
- src/datachain/func/numeric.py
- src/datachain/sql/functions/array.py
- src/datachain/sql/functions/numeric.py
- src/datachain/sql/sqlite/base.py
- tests/unit/test_func.py
Remove some operators not supported by all DBs by default. Implement bitwise functions. Improve tests.
Related to https://github.com/iterative/datachain/issues/606 (implement `XOR` function).
> Update base Func class and tests

- src/datachain/cli.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/conftest.py
- tests/func/test_ls.py
- tests/func/test_pull.py
- tests/test_cli_studio.py
Companion PR of https://github.com/iterative/studio/pull/11006
> Migrate the datasets and job urls

- src/datachain/client/fsspec.py
- src/datachain/client/local.py
- src/datachain/lib/convert/flatten.py
- src/datachain/lib/convert/unflatten.py
- src/datachain/lib/convert/values_to_tuples.py
- src/datachain/lib/utils.py
- src/datachain/query/dataset.py
- Add some missing type hints.
> add some missing type hint

- tests/examples/test_examples.py
Fixes failing CI for example test.
https://github.com/iterative/datachain/actions/runs/12250757476/job/34174241011
> test-examples: pre-download nltk data

- README.rst
Move getting started up a bit to make it more visible and break the wall of text a bit. We'll add a quick example here soon.
> Move getting started up a bit to make it more visible

- src/datachain/lib/dc.py
- src/datachain/lib/file.py
> Remove duplication in 'FileType' type definition

- docs/quick-start.md
It mitigates #740
It has to be reverted once #740 is solved
> quick-start: use anon for GCP

- README.rst
> add code to readme

- tests/unit/test_session.py
> Test for empty session name

- mkdocs.yml
- pyproject.toml
- Closes https://github.com/iterative/datachain/issues/690
> fix(navigation): lock mkdocs-material version

- src/datachain/progress.py
> chore(ui): rename env var to datachain

- .github/workflows/tests-studio.yml
Production is currently running 26.8.
> update clickhouse-server image to match production

- docs/index.md
follow up to #799, makes the corresponding change to the docs
> fix duplicate typo in docs

- src/datachain/data_storage/warehouse.py
Trying to revert based on https://github.com/iterative/datachain/pull/804#discussion_r1908131440
> fix(db): revert use_new_connection=True

- src/datachain/client/s3.py
Counterpart to https://github.com/iterative/studio/pull/11188
> fix(s3): pass region name down to fs

- src/datachain/lib/dc.py
Improve docs a bit on merge. I keep forgetting how to put function into merge condition.
> docs(merge): add examples with Func object

- src/datachain/lib/file.py
https://github.com/iterative/datachain/blob/ac50585ee6a771bfd5fe3cfaa063946dbff7b072/src/datachain/lib/file.py#L45-L48
> file: raise error

- src/datachain/cli/__init__.py
- src/datachain/cli/parser/__init__.py
- src/datachain/cli/parser/job.py
- src/datachain/cli/parser/studio.py
- src/datachain/cli/parser/utils.py
- src/datachain/cli/utils.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/test_cli_studio.py
Reference document: https://docs.google.com/document/d/1_QeMQ1NsguHSRSyJpF2n-1s57SHSuiyGzl10q9d1UaE/edit?usp=sharing
- **Rename studio to auth for cli command**
- **Drop aws_endpoint_url option**
- **Fix sources argument for cp**
- **Fix anonymous arg help**
- **Update cached list of files for the sources**
- **Reorder verbose and quiet**
- **Path to a directory or file to put data to**
> Second iteration of cli command help

- tests/unit/lib/test_datachain_merge.py
I merged #832 into `main` without first updating the branch.
> import Int into test_datachain_merge (fix tests broken on bad merge)

- src/datachain/cache.py
- src/datachain/catalog/catalog.py
- src/datachain/client/fsspec.py
- src/datachain/client/local.py
- src/datachain/lib/pytorch.py
- src/datachain/lib/udf.py
- src/datachain/nodes_fetcher.py
- tests/unit/test_cache.py
- tests/unit/test_pytorch.py
It's too verbose for my taste, and adds nothing.
> rename DataChainCache to Cache

- src/datachain/client/fsspec.py
- src/datachain/lib/file.py
from comments in https://github.com/iterative/datachain/pull/850
> use posixpath in upload methods

- src/datachain/remote/studio.py
companion to https://github.com/iterative/studio/pull/11286 - details there
> remove dataset_stats from studio client

- src/datachain/func/conditional.py
currently broken on main - https://github.com/iterative/datachain/actions/runs/13066831041
> fix docs build

- src/datachain/catalog/catalog.py
- src/datachain/cli/__init__.py
- src/datachain/cli/commands/__init__.py
- src/datachain/cli/commands/datasets.py
- src/datachain/cli/parser/__init__.py
- src/datachain/dataset.py
- src/datachain/remote/studio.py
- tests/func/test_catalog.py
- tests/func/test_datachain.py
- tests/func/test_datasets.py
As discussed here: https://github.com/iterative/studio/pull/11286/files#r1936662793
> drop dataset stats from catalog and cli

- src/datachain/remote/studio.py
- tests/test_cli_studio.py
Counterpart to https://github.com/iterative/studio/pull/11287
> fix(api): fix param name for consistency in delete api

- docs/references/toolkit.md
- mkdocs.yml
Add "Toolkit" page to the "API Reference" section.
> Update docs: add toolkit page

- src/datachain/cli/parser/__init__.py
- src/datachain/cli/parser/job.py
- src/datachain/cli/parser/studio.py
- src/datachain/cli/parser/utils.py
- src/datachain/studio.py
- tests/unit/test_cli_parsing.py
main> #802 > #826 > #861 > #888
--------------
Document for output: 
- https://docs.google.com/document/d/1_QeMQ1NsguHSRSyJpF2n-1s57SHSuiyGzl10q9d1UaE/edit?tab=t.0#heading=h.dgvxpumnivkj
- **Add custom argparse and help formatter**
- **Rename stuffs**
> Add custom error and CustomHelpFormatter for cli

- pyproject.toml
Related: https://github.com/iterative/studio/issues/11282#event-16257846720
> Upgrade iterative telemetry to reduce noise

- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/func/test_pull.py
This adds missing parameter and behavior to the documentation.
Before:
After:
> Add documentation for new from_dataset behavior

- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- tests/func/test_datachain.py
This fixes the case where the path is passed to to_storage
> Fix the to_storage for relative path

- .github/workflows/tests.yml
FFmpeg setup is broken for now because of rate limiting.
> Fix ffmpeg setup in GitHub CI

- .github/workflows/tests.yml
- noxfile.py
Missed during #941.
Also get rid of `dev` session from noxfile while I am at it.
> ci: fix conditional check for hf

- docs/references/remotes.md
- mkdocs.yml
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
After the discussion over #936 , this pull request instead adds a proper
documentation for accepted parameters for client config
> Document remote interaction properly

- src/datachain/client/fsspec.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- src/datachain/lib/listing.py
- tests/func/test_datachain.py
This allows us to pass Path like objects for from_storage and other
places.
Closes #729
> Make from_storage support path object

- src/datachain/cli/parser/studio.py
- src/datachain/studio.py
This adds login logout token to the local config if --local flag is
specified.
Related to https://github.com/iterative/dvc/issues/10679
> Add local flag to login and logout auth

- src/datachain/lib/listing.py
Related: https://github.com/iterative/datachain/pull/856#discussion_r1989389883
> refactor(listing): pull glob check out of `_isfile`

- src/datachain/catalog/catalog.py
- src/datachain/dataset.py
- src/datachain/lib/dc.py
- tests/conftest.py
- tests/unit/lib/test_datachain.py
This adds two arguments named `studio: bool` and `team: str|None` for
the datasets class method.
Closes #952
> Add studio support in DataChain.datasets()

- src/datachain/lib/file.py
- tests/unit/lib/test_signal_schema.py
* Added 'etag', 'is_latest', 'last_modified', and 'location' to the hidden fields in the File class.
* Updated unit tests to reflect changes in hidden fields for the File model.
Studio:
ds.show:
Closes #979
> Update hidden fields in File model and corresponding tests

- tests/conftest.py
- tests/func/test_datachain.py
Extracted from @shcheklein's original code at #4
> Add fixture to run tasks from `datachain-worker` queue

- docs/examples.md
- docs/quick-start.md
- src/datachain/func/aggregate.py
- src/datachain/lib/dc/datachain.py
- src/datachain/lib/dc/utils.py
Fixes docs a bit to reflect the current naming of the file object attributes.
> fix(docs): file name to file path

- src/datachain/lib/dc/datachain.py
Minor update, to include an operation that is not obvious at all to exist ....
> chore(docs): add in_ operation example

- src/datachain/lib/dc/records.py
insert_rows does not do chunking, so we go OOM with very large no. of records.
> read_records: insert records in batches

- src/datachain/func/array.py
- src/datachain/func/func.py
- src/datachain/sql/functions/array.py
- src/datachain/sql/sqlite/base.py
- tests/func/test_func.py
- tests/unit/sql/test_array.py
Needed in this PR: https://github.com/iterative/studio/pull/11524
See also tests for usage.
(this is better and more generic implementation of https://github.com/iterative/datachain/pull/1057)
> Add 'array.get_element' function

- .github/workflows/benchmarks.yml
- .github/workflows/tests.yml
Until this is fixed https://github.com/wntrblm/nox/issues/953
> fix(tests): pin uv in tests until nox issue is fixed

- src/datachain/query/dispatch.py
Fix for the error:
```
UDF task failed: Code: 62.
DB::Exception: Syntax error: failed at position 262145 (',') (line 3, col 262054): , 663538, 663539, 663540, 663541, 663542, 663543, 663544, 663545, 663546, 663547, 663548, 663549, 663550, 663551, 663552, 663553, 663554, 663555, 663556, 663557. Max query size exceeded: ','. Stack trace:
0. ./contrib/llvm-project/libcxx/include/vector:676: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c30f0a4
1. ./src/Common/Exception.h:104: DB::Exception::createDeprecated(String const&, int, bool) @ 0x000000000c371920
2. ./build_docker/./src/Parsers/parseQuery.cpp:405: DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long, unsigned long) @ …
```
> Fix fetching dataset rows

- src/datachain/data_storage/warehouse.py
- tests/func/test_warehouse.py
Continuation of https://github.com/iterative/datachain/pull/1082 & https://github.com/iterative/studio/pull/11552.
> Use underscores for semantic versions in table names

- docs/commands/job/run.md
- src/datachain/cli/parser/job.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/test_cli_studio.py
> Add priority option to run the job

- pyproject.toml
It was fixed server-side [here](https://github.com/huggingface/huggingface_hub/issues/3064).
> Remove 'huggingface_hub' version constraint

- src/datachain/func/array.py
- src/datachain/func/func.py
- src/datachain/sql/functions/array.py
- src/datachain/sql/sqlite/base.py
- tests/func/test_func.py
- tests/unit/sql/test_array.py
> Add 'slice' and 'join' array functions

- src/datachain/query/dataset.py
- tests/func/test_datachain.py
Fix dependencies when `.persist()` is used in the chain.
> Fixing dataset dependencies when persist is used

- src/datachain/lib/dc/datachain.py
Replaces https://github.com/iterative/datachain/pull/1070
> improve setup docs to make it clear that callable is expected

- src/datachain/query/dispatch.py
- tests/func/test_datachain.py
- tests/unit/lib/test_datachain.py
> Fix agg() in parallel mode

- src/datachain/cache.py
- src/datachain/client/fsspec.py
- src/datachain/client/local.py
- src/datachain/lib/arrow.py
- src/datachain/lib/file.py
- src/datachain/lib/tar.py
- src/datachain/lib/webdataset.py
- tests/func/test_datachain.py
- tests/func/test_file.py
- tests/unit/lib/test_file.py
Reverts iterative/datachain#1110
Some tests are failing, need more tests on the datachain side.
> Revert "Improve file path validation"

- src/datachain/lib/file.py
- tests/func/test_datachain.py
Fixes prefetch for Tar (and VFile in general) + some cleanup.
Tar processing is broken at the moment by default since prefetch attempts do download the VFile itself which breaks on asserts in downloader:
```python
async def _put_in_cache(self, file: "File", *, callback: "Callback" = None) -> None:
assert not file.location
if file.etag:
etag = await self.get_current_etag(file)
if file.etag != etag:
raise FileNotFoundError(
f"Invalid etag for {file.source}/{file.path}: "
f"expected {file.etag}, got {etag}"
)
await self.cache.download(file, self, callback=callback)
```
mind: 
`assert not file.location`
> fix(tar): prefetching parent for vfiles

- docs/commands/job/run.md
- src/datachain/cli/parser/job.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/test_cli_studio.py
This uses https://github.com/iterative/studio/pull/11698 to pass compute
cluster id to studio to create a job
> Pass cluster id as a parameter in CLI jobs run

- src/datachain/lib/dc/datachain.py
See https://github.com/iterative/datachain/issues/1145
> Update filter docs with conjunction operators

- docs/commands/job/run.md
- src/datachain/cli/parser/job.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/test_cli_studio.py
* https://github.com/iterative/datachain/pull/1144#discussion_r2138938419
* https://github.com/iterative/studio/pull/11762
> Reference compute clusters by name

- examples/llm_and_nlp/hf-dataset-llm-eval.py
- src/datachain/client/hf.py
Fixes HF filesystem (writes were failing silently), also updates and fixes HF failing example tests.
I'm not 100% sure what was the intention to skip `open` in the original `fsspec` wrapper. This fixes it (otherwise all writes were silently ignored pretty much). I'll follow up with fsspec's maintainers to see if it should be fixed upstream instead.
Also, update example to fix a bunch of other issues in the pipeline.
> fix(hf): fix fs wrapper to handle write
