iterative/datachain

- pyproject.toml
- tests/func/test_datachain.py
DateTime in clickhouse is based on Unix time, and has no sub-second precision.
So I am flooring the mtime. Also had to change the timezone to use `pytz.UTC` for some reason (still not sure why that is the case), but wanted to unblock the CI.
> fix test for ch wrt datetime precision

- tests/func/test_datachain.py
- tests/unit/lib/test_file.py
- tests/utils.py
Adding missing tests from https://github.com/iterative/datachain/pull/135 :
- Exporting images
- `File.write()` 
- `TextFile.write()`
- `ImageFile.write()`
> Adding tests for exporting image files and `File.write()`

- src/datachain/query/dataset.py
- tests/func/test_dataset_query.py
This adds small fix for using new column added in `.mutate()` in `.order_by(). 
Example:
```python
from datachain.lib.dc import C, DataChain
(
DataChain.from_storage("s3://ldb-public/remote/data-lakes/dogs-and-cats/", anon=True)
.mutate(size_10x = C("file__size") * 10)
.order_by("size_10x")
.save("example")
)
```
> Fix for using new column from `.mutate()` in `.order_by()`

- .github/workflows/tests.yml
- tests/conftest.py
The CI is flaky because of colima/docker usage, which does not seem to be stable on macOS. Also, we already run those tests on Linux, so we don't really need to run it on macOS.
Closes #51.
> ci: disable azure and gs remote tests on macOS

- src/datachain/lib/file.py
- tests/unit/lib/test_file.py
Simple rename of `.write()` to `.save()` to not break built-in `io.FileIO` interface which our `File` should follow.
> Renaming `File.write()` to `File.save()`

- src/datachain/catalog/catalog.py
- tests/func/test_catalog.py
- tests/unit/lib/test_datachain.py
Related to:
https://github.com/iterative/dvcx/issues/1488#issuecomment-2139318338
https://github.com/iterative/dvcx/pull/1485#issuecomment-2133400527
(see links and discussion in those threads as well).
Trying to make things like:
```
datachain ls neurips
```
and 
```
datachain ls neurips/
```
behave the same way and avoid indexing the parent directory. I think is the most expected thing from the user perspective. Otherwise a query like `datachain ls neurips` now can index an unpredictable amount of all sorts of files in the parent directory, while still producing the exact same result at the end as `datachain ls neurips/`.
Same goes for `DataChain.from_storage("gs://datachain-demo/50k-laion-files/")` should be the same as `gs://datachain-demo/50k-laion-files` (no slash at the end).
> storage: index as a dir if no glob

- pyproject.toml
- src/datachain/data_storage/schema.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/examples/test_wds_e2e.py
- tests/func/test_datasets.py
- tests/func/test_feature_pickling.py
- tests/unit/lib/test_datachain_merge.py
- tests/unit/lib/test_feature.py
- tests/unit/test_module_exports.py
This fixes a variety of warnings that show up when running tests:
- Uses `selected_columns` instead of `columns` in select statements to avoid this SQLAlchemy warning: `  /home/runner/work/datachain/datachain/.nox/tests-3-9/lib/python3.9/site-packages/datachain/query/dataset.py:1255: SADeprecationWarning: The SelectBase.c and SelectBase.columns attributes are deprecated and will be removed in a future release; these attributes implicitly create a subquery that should be explicit.  Please call SelectBase.subquery() first in order to create a subquery, which then contains this attribute.  To access the columns that this SELECT object SELECTs from, use the SelectBase.selected_columns attribute. (deprecated since: 1.4)`
- Renames Test... classes to no longer start with Test as this causes …
> Fixing test warnings

- examples/computer_vision/fashion_product_images/4-inference.ipynb
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
Partial fix for #103. Also includes a unit test for `DataChain.union()` which was mentioned there but appears to work.
Note that `chain1.subtract(chain2)` doesn't actually work for real datasets, even though the unit tests pass. The workaround in to use `on` as in `new.subtract(old, on=["file.name"])`.
> Update DataChain.subtract() to work without legacy file signals

- pyproject.toml
- src/datachain/lib/convert/flatten.py
- src/datachain/sql/sqlite/base.py
- src/datachain/sql/sqlite/types.py
Let's profile laion embeddings generation from `gs://dvcx-datacomp-small/metadata` bucket.
List bucket:
```
$ gsutil ls -l gs://dvcx-datacomp-small/metadata
3106844080  2024-01-15T15:37:25Z  gs://dvcx-datacomp-small/metadata/0020f0cbd157d470aa56bea08e304b90.npz
120845372  2024-01-15T15:28:20Z  gs://dvcx-datacomp-small/metadata/0020f0cbd157d470aa56bea08e304b90.parquet
...
673764696  2024-01-15T15:29:52Z  gs://dvcx-datacomp-small/metadata/036d6b9ae87a00e738f8fc554130b65b.npz
26585624  2024-01-15T15:27:58Z  gs://dvcx-datacomp-small/metadata/036d6b9ae87a00e738f8fc554130b65b.parquet
TOTAL: 52 objects, 81707590807 bytes (76.1 GiB)
$
```
Pre-download "small" `643Mb`, `109662` rows `npz` file (just to make it easier to profile):
```
$ mkdir -p dvcx-datacomp-small/metadata
$ gsutil cp -v …
```
> Optimizations: low-hanging fruits

- src/datachain/lib/file.py
- tests/func/test_datachain.py
`S3Client.create_fs()` tries to sign an s3 uri, which might hit the remote. So, all of the current
`get_destination_path` and `get_path` tests are
hitting AWS S3, which might fail if you don't have credentials set.
https://github.com/iterative/datachain/blob/0ed1e2cf2e66ba1913301c81b0a907941b0c6953/src/datachain/client/s3.py#L46
So this PR tries to avoid constructing them wherever possible (at least in these path operations).
An alternative fix might be to run tests inside `s3_server`.
Also removes one test that hits gcs.
> avoid instantiating filesystem for path operations

- src/datachain/data_storage/metastore.py
- src/datachain/data_storage/sqlite.py
This removes get_possibly_stale_jobs in favor of get_in_progress_jobs
introduced recently.
Relates to https://github.com/iterative/studio/issues/10344
> Remove get_possibly_stale_jobs from metastore

- examples/llm_and_nlp/llm-claude-aggregate-query.py
- examples/llm_and_nlp/llm-claude-simple-query.py
- examples/llm_and_nlp/llm-claude.py
Small UX improvement for these scripts when a user tries to run them without first setting an API key. Without an API key they will be presented with something like:
```
Processed: 50 rows [00:00, 17568.50 rows/s]
============== Error in user code: 'Mapper' ==============
Traceback (most recent call last):
File "/datachain/src/datachain/lib/udf.py", line 156, in process
return self._func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/datachain/examples/llm_and_nlp/llm-claude.py", line 23, in <lambda>
claude=lambda client, file: client.messages.create(
^^^^^^^^^^^^^^^^^^^^^^^
File "/datachain/.env/lib/python3.12/site-packages/anthropic/_utils/_utils.py", line 277, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File …
```
> prevent cryptic error messages when running llm claude examples

- src/datachain/lib/convert/flatten.py
- src/datachain/sql/types.py
- tests/unit/lib/test_datachain.py
- tests/unit/lib/test_feature.py
The problem was if we had `list[list[SomeModel]]` as a field in our custom model as flattening worked only for one level of lists with models.
This PR fixes `flatten(obj)` function to be able to flatten any number of nested lists and adds tests.
> Fix for nested lists of models in schema

- docs/references/udf.md
- src/datachain/lib/dc.py
- src/datachain/lib/settings.py
- src/datachain/lib/udf.py
- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
Fixes #84.
I think we should keep open #170. That request seems to be specifically about using futures to batch individual results using the existing `.map` without needing a separate `.batch_map()`. I think `.batch_map()` may be both simpler to implement and explain for now, but I think we could come back to the ideas in #170 in the future.
> Support for `DataChain.batch_map()`

- src/datachain/lib/signal_schema.py
- tests/unit/lib/test_datachain.py
closes #209
The issue is that `distinct` strips the parent path from the `signals_schema`. E.g. if we do distinct by `file.name` then `file` is removed from the schema. `select` then fails because it cannot find `file` in the tree.
see the `test_select_distinct` test to see exactly what is being fixed.
> fix select then distinct chain

- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
Closes #219 by fixing the error introduced in #206. The approach now more closely aligns with the existing mechanics around `clone`.
> do not modify datachain max limit in show

- src/datachain/catalog/catalog.py
- src/datachain/cli.py
- src/datachain/data_storage/metastore.py
- src/datachain/data_storage/warehouse.py
- src/datachain/query/dataset.py
- tests/func/test_catalog.py
Since the cleanup_temp_tables currently takes the argument of the tables
and drop those tables, cleanup_tables makes more sense.
Related to https://github.com/iterative/studio/pull/10365/files#r1697793625
> Rename cleanup_temp_tables to cleanup_tables in warehouse and catalog

- examples/get_started/json-csv-reader.py
- src/datachain/lib/arrow.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- tests/unit/lib/test_arrow.py
- tests/unit/lib/test_datachain.py
Fixes #210 
Writes the first nrows to a local temp file to avoid the pyarrow issues with partial reads from cloud filesystems. This means nrows won't work with parquet or other binary formats.
I find this fix hacky but a quick look at pyarrow makes me think it would be much more effort to fix it there, so this might be the best we can do for now.
> Arrow nrows fix

- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
Follow up to [this comment](https://github.com/iterative/datachain/pull/225#discussion_r1701687436)
> only combine final step for limit

- tests/conftest.py
- tests/func/test_catalog.py
- tests/func/test_pull.py
- tests/test_query_e2e.py
- tests/unit/lib/test_datachain.py
- tests/unit/test_database_engine.py
- tests/unit/test_id_generator.py
- tests/unit/test_listing.py
- tests/unit/test_storage.py
- tests/utils.py
This provides some improvements to the "Skip if not running on SQLite" option for tests - this changes the skip function to a decorator (to avoid fixture and other test setup if not needed), and also adds an auto-skip for any test using the `sqlite_db` fixture, as these tests don't use other data storages anyways, so running them not on SQLite is unnecessary.
This has been tested locally, including with ClickHouse, and is a followup to #229 and has a temporary fix for #251 (increasing the timeout on the query end-to-end test, since I can't reproduce the problem locally.)
> Skip if not SQLite Improvements

- .github/workflows/tests.yml
If Studio repo have branch with the same name PR have use it instead of hardcoded `develop` branch.
It was tested in [this PR](https://github.com/iterative/datachain/pull/252), see [this action](https://github.com/iterative/datachain/actions/runs/10290404411/job/28480287352?pr=252).
> Autodetect Studio branch

- .github/workflows/tests.yml
Follow-up for the https://github.com/iterative/datachain/pull/253
`main` Studio branch should not be used in `main` datachain branch 🤦
See also: https://github.com/iterative/datachain/actions/runs/10296449508/job/28497811566
> Autodetect Studio branch fix for 'main' branch

- src/datachain/catalog/catalog.py
- src/datachain/client/fsspec.py
- src/datachain/client/local.py
- tests/unit/test_client.py
This seem to not be used so trying to remove it
> Removing `metastore` argument from `Client.parse_url()`

- src/datachain/data_storage/warehouse.py
- src/datachain/lib/udf.py
- src/datachain/query/batch.py
- src/datachain/query/dataset.py
- src/datachain/query/dispatch.py
- src/datachain/query/queue.py
- src/datachain/query/udf.py
- src/datachain/utils.py
- tests/unit/test_udf.py
"Parallel" mode is not optimal now. It took more time and much more memory (script can even be killed by OOMKiller). In this PR we are going to profile and optimize parallel mode.
---
Test dataset with `109662` rows:
```
$ ls -l dvcx-datacomp-small/metadata-small
total 1315952
-rw-r--r--@ 1 vlad  staff  673764696 Jul 24 17:15 036d6b9ae87a00e738f8fc554130b65b.npz
$
```
Test query `laion_emb.py`:
```python
from datachain.lib.dc import DataChain
from datachain.lib.webdataset_laion import process_laion_meta
(
DataChain.from_storage("dvcx-datacomp-small/metadata-small/")
.gen(emd=process_laion_meta)
.map(stem=lambda file: file.get_file_stem(), params=["emd.file"], output=str)
.save("laion_emb")
)
```
```
$ time python laion_emb.py
Processed: 1 rows [00:00, 2532.79 rows/s]
Download: 643MB …
```
> Parallel UDF optimizations

- src/datachain/lib/dc.py
- tests/func/test_datachain.py
- tests/unit/lib/test_datachain.py
Closes https://github.com/iterative/datachain/issues/237 + simplifies the code a bit and makes sure that column names are preserved in `df` even if there are no values - consistently across flatten and non-flatten version.
```
files = [File(size=s, path=p) for p, s in zip(list("abcde"), range(5))]
DataChain.from_values(file=files).limit(0).show()
```
returns:
```
Empty result
Columns: [('file', 'source'), ('file', 'path'), ('file', 'size'), ('file', 'version'), ('file', 'etag'), ('file', 'is_latest'), ('file', 'last_modified'), ('file', 'location'), ('file', 'vtype')]
```
(similar to how pandas returns the list of columns to make it easier to debug)
Once thing that I was not able to imitate for now is a schema-less (no columns, no-values DataChain), but let's consider this as a minor edge …
> fix(to_pandas): handle empty datachain in to_pandas (and show)

- src/datachain/data_storage/sqlite.py
- src/datachain/query/schema.py
- tests/func/test_dataset_query.py
- tests/unit/lib/test_schema.py
Closes https://github.com/iterative/datachain/issues/223
Example:
```python
filter(
C("file.name").regexp("dog\\.txt$")
)
```
Need to test if it works on CH the same way and regexp supported is more or less the same.
> feat(column): add regexp match

- examples/llm_and_nlp/unstructured-text.py
- pyproject.toml
This PR fixes the unstructured-text nlp example. Tl;dr is that the new version of `nltk` does not play nicely with `unstructured`.
> fix unstructured-text example

- README.rst
> readme - json-pairs

- src/datachain/catalog/catalog.py
Borrowing the logic from https://github.com/iterative/studio/pull/10466/files, this ensures that only the relevant schema (for files) is passed during deserialization. As a result, any other issues or errors during deserialization won’t block the essential function itself. 
Closes https://github.com/iterative/studio/issues/10438 , https://github.com/iterative/studio/issues/10441
> chore: Deserialize only file signals in get_file_signals

- tests/unit/lib/test_datachain_merge.py
Goes on top of #296
Leftover from https://github.com/iterative/datachain/pull/254 and https://github.com/iterative/datachain/pull/249 being merged at roughly the same time
> remove erroneous skip_if_not_sqlite calls

- examples/computer_vision/openimage-detect.py
- examples/get_started/common_sql_functions.py
- src/datachain/sql/sqlite/base.py
- tests/unit/sql/test_path.py
Follow up to https://github.com/iterative/datachain/pull/101/files#r1697409039 and https://github.com/iterative/datachain/pull/101/files#r1709153373
This PR updates the compiled `file_stem` function to accept a full path instead of expecting users to write `path.file_stem(path.name(C("file.path")))`. This change leads to (slightly) better SQL being generated as well.
For comparison I've put the current and newly generated SQL below:
```sql
rtrim(
substr(
ltrim(
substr(
source__file__path,
length(
rtrim(
rtrim(
source__file__path,
replace(source__file__path, :param_1, :param_2)
),
:param_1
)
) + :length_16
),
:param_1
),
:substr_2,
length(
ltrim(
substr(
source__file__path,
length(
rtrim(
rtrim(
source__file__path,
replace(source__file__path, :param_1, :param_2)
),
:param_1
)
) + …
```
> have file_stem accept a full path

- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
follow up to https://github.com/iterative/datachain/pull/216
closes https://github.com/iterative/dvcx/issues/1202
This PR changes the behaviour of our union operator to throw an obvious error (in all db implementations) when there is a mismatch in columns between the two chains being unioned. Previously we "cast"ed all columns with missing values to nulls. This only worked for SQLite as we do not/do not want to store nulls in Clickhouse. For more details see the above issue.
> standardise union behaviour between db implementations

- pyproject.toml
The most recent version of `unstructured` has moved to `nltk==3.9.1`. We want to use that version of `unstructured` now so we need to remove the pin.
> remove nltk pin

- pyproject.toml
Closes #334
`msgpack` is imported [here](https://github.com/iterative/datachain/blob/71c942c43cc17d8457ee72cbb4765d10fb14eecc/src/datachain/query/queue.py#L8) so it should be a core dependency
> move msgpack to core dependencies

- src/datachain/lib/dc.py
- tests/unit/lib/test_datachain.py
Fixes #328 
~`to_pandas(flatten=True)` now returns columns in the same way as `to_records` and in the same way we store them in the DB (to fix the bug and for consistency)~ 
changing this use `.`. It is simpler for end users and we don't want them to see DB details (at least it's not how our API operates atm).
> use default delimiter to flatten columns

- src/datachain/data_storage/sqlite.py
`execute_str` is currently the only `execute` function in `SQLiteDatabaseEngine` not to have the `@retry_sqlite_locks` decorator added.
This update should help with intermittent errors in the test suite that look like [this](https://github.com/iterative/datachain/actions/runs/10483364346/job/29035966839#step:7:165).
> add retry locks to SQLiteDatabaseEngine  execute_str

- src/datachain/lib/dc.py
Fixes: #298
Docs: mutate() can rename columns with example
> Mutate can rename columns

- src/datachain/catalog/catalog.py
This change breaks the read by reading each character and
yielding the breaks in <CR> or new lines instead of just waiting on new
line.
Studio PR: https://github.com/iterative/studio/pull/10509
> Handle carriage return to support progress bar in logs

- src/datachain/data_storage/schema.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
We use [convert_rows_custom_column_types](https://github.com/iterative/datachain/blob/dfa206812227d5ded173a33d1998c98161368b06/src/datachain/data_storage/schema.py#L49-L76) in [dataset_rows_select](https://github.com/iterative/datachain/blob/dfa206812227d5ded173a33d1998c98161368b06/src/datachain/data_storage/sqlite.py#L654C9-L658), but did not use it in `dataset_select_paginated`. This PR fixes this.
> Convert custom columns types in dataset_select_paginated

- src/datachain/lib/convert/python_to_sql.py
Fix for https://github.com/iterative/datachain-examples/issues/7
Special case for `Union[str, Literal[...]]` type.
(tests to be added if this fix is OK)
> Convert 'Union[str, Literal[...]]' type to string

- .github/workflows/tests.yml
The suite timed out on windows here: https://github.com/iterative/datachain/actions/runs/10516264552/job/29138114753?pr=346
> increase timeout of datachain tests in CI

- src/datachain/query/dataset.py
- src/datachain/query/session.py
Fix for https://github.com/iterative/datachain/issues/327
See [this comment](https://github.com/iterative/datachain/issues/327#issuecomment-2311622854).
Closes #343.
> Fix empty 'save()' as query last statement

- src/datachain/lib/signal_schema.py
- tests/func/test_feature_pickling.py
- tests/unit/lib/test_signal_schema.py
This adds the ability to save and restore model classes (feature classes) to SignalSchema, by saving these in a `_custom_types` key, then restoring them by creating a dynamic pydantic class with the stored definition. This is useful for when a custom model class is declared and used to create a dataset, but then this dataset is viewed or used in a DataChain somewhere else where this original definition is not available. This will also be useful for any other import / export functions where the original types may need to be changed, such as in parquet import/export, although this will be included in a followup/separate PR(s) to avoid this getting too complex and keep these PRs focused.
This has been tested locally and with Studio. This fixes https://github.com/iterative/studio/issues/10417 …
> Adding Custom Type (De)Serialization to Signal Schema

- .github/workflows/tests.yml
After https://github.com/iterative/datachain/pull/347 30 minutes is still not enough for Windows: 
- https://github.com/iterative/datachain/actions/runs/10566407286/job/29273135592?pr=354
- https://github.com/iterative/datachain/actions/runs/10578660222/job/29309290443
> increase timeout of datachain tests in CI (Windows)

- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
Fix: DataChain.subtract() on differently named columns 
Fixes #181
> improve datachain subtract

- src/datachain/catalog/catalog.py
- tests/func/test_catalog.py
This fixes `get_file_signals` for proper custom type handling, removing the workaround previously added due to lack of custom type serialization / deserialization. This also adds a test to ensure these types are processed correctly, so that this can be caught earlier than Studio end-to-end tests.
This has been tested with my local Studio install to work with both old (no custom types) datasets and new datasets (with custom types) with both custom type display and image preview working. This is a followup to #348 and is part of https://github.com/iterative/studio/issues/10417 and https://github.com/iterative/studio/issues/10547
> Fixing get_file_signals for custom types

- pyproject.toml
- src/datachain/client/fsspec.py
- src/datachain/client/hf.py
- src/datachain/lib/arrow.py
- tests/unit/lib/test_arrow.py
Closes #368.
Example:
```python
>>> DataChain.from_parquet("hf://datasets/ylecun/mnist/**.parquet").show()
Preparing: 2 rows [00:00, 2100.83 rows/s]
Processed: 2 rows [00:00, 3178.71 rows/s]
Cleanup: 2 tables [00:00, 4447.83 tables/s]
Preparing: 2 rows [00:00, 1408.43 rows/s]
Processed: 2 rows [00:00, 2016.01 rows/s]
Parsed by pyarrow: 10000 rows [00:00, 10172.99 rows/s]
Parsed by pyarrow: 60000 rows [00:03, 18752.09 rows/s]
Processed: 2 rows [00:04,  2.21s/ rows]0000.68 rows/s]
Generated: 70000 rows [00:03, 19081.33 rows/s]
Cleanup: 5 tables [00:00, 63.35 tables/s]
source                                          source   source                                    source                                    source    source  \
file                                            file     file …
```
> Support for reading from huggingface hub with `hf://` filesystem

- src/datachain/lib/listing.py
- src/datachain/node.py
> Simplify datachain.lib.listing by reusing Cilent.scandir()

- src/datachain/data_storage/sqlite.py
Quick fix for `DEBUG_SHOW_SQL_QUERIES` when queries with `src/datachain/lib/meta_formats.py` `read_meta` are used. It's broken since we have:
`# ugly hack: datachain is run redirecting printed outputs to a variable`
there, where we execute command output. It breaks if there are some debug statements.
We need to get back and review `src/datachain/lib/meta_formats.py`.
> Use stderr for sql debug prints

- src/datachain/catalog/catalog.py
- src/datachain/cli.py
- src/datachain/query/dataset.py
- src/datachain/query/metrics.py
- tests/func/test_metrics.py
Partially fixes #384. (We don't save metrics yet if they are not run as a job).
> metrics: save metrics in realtime

- src/datachain/data_storage/metastore.py
Using `job_class` private property instead of `Job` to avoid issues in SaaS where we have extended class with additional fields.
> Using job class instead of hardcodced `Job`

- src/datachain/catalog/catalog.py
- src/datachain/cli.py
- src/datachain/query/dataset.py
- tests/func/test_catalog.py
- tests/func/test_query.py
- tests/scripts/feature_class.py
- tests/test_query_e2e.py
Part of #360.
After removing last expression wrapping, we will not be able to get access to the dataset query, nor we'll be able to show previews.
Also, CLI is hidden at the moment. So, it is better if we disable the preview support altogether for now, as this simplifes a lot for #360.
> cli: remove preview from `datachain query` command

- src/datachain/catalog/catalog.py
- src/datachain/job.py
- src/datachain/query/dataset.py
- tests/func/test_catalog.py
- tests/func/test_query.py
Now, we fetch all dataset versions created with a given `job_id`, and then choose the latest one by its `datetime`. (If there are multiple dataset versions with the same datetime, the first one encountered is used but that may be rare).
This removes the need for using a pipe to read and write dataset version from a script, which is too complicated.
> query: remove use of pipe for communication

- src/datachain/catalog/catalog.py
- src/datachain/query/dataset.py
- tests/func/test_catalog.py
- tests/func/test_query.py
This PR removes the requirement for the last statement to be either an expression or an instance of DatasetQuery.
After this PR, scripts without a final expression will function properly in both Datachain and Studio.
The last statement wrappers and related infrastructure will be removed in subsequent PRs.
However, this PR demonstrates that everything already works and is usable.
```python
from datachain.query import DatasetQuery
DatasetQuery("s3://dql-test-e2e", catalog=catalog).save("temp")
print("hello world!")
```
```console
$ datachain query script.py
Processed: 1 rows [00:00, 512.00 rows/s]
Generated: 9 rows [00:00, 4950.00 rows/s]
Cleanup: 1 tables [00:00, 3498.17 tables/s]
Saving: 279 rows [00:00, 68945.43 rows/s]
hello world!
```
> do not require last statement to be an expression or an instance of DatasetQuery

- pyproject.toml
- src/datachain/lib/meta_formats.py
- tests/func/test_meta_formats.py
Latest update of pydantic broke `read_schema()`, which fails to correctly resolve annotations.
Please read more here: https://github.com/pydantic/pydantic/pull/10113#issuecomment-2334100659.
> unpin pydantic, use python API for datamodel_codegen

- examples/multimodal/clip_inference.py
- examples/multimodal/wds.py
- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain_merge.py
Closes #299
This PR allows users to merge DataChains using `Column`s and/or expressions (e.g. `path.file_stem(dc.c("source.path"))`). Examples of the new syntax are shown in `examples/multimodal/clip_inference.py` & `examples/multimodal/wds.py`. Once this change has been merged I will make the appropriate changes in the `datachain-examples` repo.
It should be noted that the change is backwards compatible and `merge` will continue to accept strings for the `on` and `right_on` parameters.
> allow merge on expressions

- pyproject.toml
When I use Python 3.12, I receive many warnings about the following issue:
```
/Users/lifei/PycharmProjects/datachain/.nox/tests-3-12/lib/python3.12/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
```
The reason is that the …
> remove pytest_asyncio lib

- examples/get_started/udfs/stateful.py
This PR switches on `hf_transfer` in the stateful example. This should speed the example up.
I've also seen some intermittent failures in the CI for this example. Hopefully, this helps with reliability.
> use hf transfer in stateful example

- pyproject.toml
- src/datachain/lib/clip.py
- src/datachain/lib/image.py
- src/datachain/lib/text.py
- tests/func/test_pytorch.py
When I run the tests, I often encounter warnings related to library dependencies. In my PR, I've ignored warnings coming from third-party libs. And if they come from our own code, I'm rewriting it.
These warnings are need to rewrite code.
```
tests/unit/lib/test_text.py: 1 warning
/Users/lifei/PycharmProjects/datachain/.nox/tests-3-12/lib/python3.12/site-packages/datachain/lib/text.py:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
tokens = torch.tensor(tokens)
tests/unit/lib/test_clip.py::test_similarity_scores_hf
tests/unit/lib/test_image.py::test_convert_image_hf
/Users/lifei/PycharmProjects/datachain/.nox/tests-3-12/lib/python3.12/site- …
```
> remove some warnings

- src/datachain/lib/webdataset.py
- src/datachain/lib/webdataset_laion.py
Every time user runs DataChain query they've got these warnings, in both CLI and Studio:
```
/Users/vlad/.virtualenvs/datachain/lib/python3.12/site-packages/pydantic/_internal/_fields.py:200: UserWarning: Field name "json" in "WDSAllFile" shadows an attribute in parent "WDSBasic"
warnings.warn(
/Users/vlad/.virtualenvs/datachain/lib/python3.12/site-packages/pydantic/_internal/_fields.py:200: UserWarning: Field name "json" in "WDSLaion" shadows an attribute in parent "WDSBasic"
warnings.warn(
```
It is noisy and looks suspicious. Also in parallel mode user gets multiple set of these warnings.
The reason why these warnings appears is in [WDSAllFile](https://github.com/iterative/datachain/compare/ignore-pydantic-parent-shadows-json-attribute-warning?expand=1#diff-efced1e58607a221158f62b6c7fa4 …
> Ignore Pydantic 'Field name "json" shadows an attribute in parent' warning

- src/datachain/catalog/catalog.py
- src/datachain/error.py
- tests/func/test_catalog.py
- tests/func/test_datasets.py
- tests/func/test_query.py
This PR hides the support for execution of last query expression behind a flag, which I plan to remove when Studio is updated.
Also, few other changes have been made to the `query` API:
1. `envs=` keyword argument has been renamed to `env`, similar to `subprocess.Popen(env=)`.
2. `python_executable` default has been changed from `None` to `sys.executable`. And it no longer accepts `None`.
3. The `query` API no longer returns `QueryResult` API. The responsibility is now with the caller, to find out latest dataset version. They are in much better place to do that, since they are the one responsible for creating a `job`.
4. On `capture_output=True`, `query` API no longer prints to the `stdout`. The `output_hook` is responsible to do so now.
5. Exceptions raised on `query` no longer have …
> disable execution of last query expression by default

- src/datachain/catalog/catalog.py
- src/datachain/data_storage/warehouse.py
- tests/func/test_catalog.py
It looks like calculating datasets stats is broken in some cases.
The way it works now is we are calculating the sum of either `file__size` or `size` fields in all dataset rows. I think `size` is not used anymore and `file__size` will works only for listings.
In this PR I am calculating `size` dataset stat as sum of all fields with name ending with `file__size`. This way we will be able to calculate listing size (`file__size` field) and other signals, like `laion.file.size`, `source.file.size`, `emd.file.size`, etc. Also we are now calculating sum of all `file.size` fields instead of calculating only one of them.
> Fix calculating datasets stats size

- tests/examples/test_wds_e2e.py
- tests/func/test_datachain.py
- tests/test_cli_e2e.py
- tests/test_query_e2e.py
Here I've switched over from catalog to test_session in a few tests and then from catalog to catalog_tmpfile in some tests that use parallel processing.
> use the correct fixtures in tests

- tests/func/test_catalog.py
See https://github.com/iterative/datachain/pull/407#discussion_r1755915341.
`stdout`/`stderr` are now always a binary stream since #407, so adjusting the mocks in the tests to account for that.
Thanks @mattseddon and @amritghimire for identifying. :)
> tests: fix mock for subprocess stdout/stderr to return BytesIO

- src/datachain/client/s3.py
- src/datachain/lib/file.py
- tests/unit/lib/test_file.py
Fix: Need resolve_files() method #301
Closes #301
> Add resolve files

- tests/unit/lib/test_datachain_bootstrap.py
unskips the test skipped [here](https://github.com/iterative/dvcx/pull/1688/files#r1669039544)
> unskip test_udf_parallel

- src/datachain/catalog/catalog.py
- src/datachain/client/fsspec.py
- src/datachain/lib/dc.py
- src/datachain/lib/listing.py
- src/datachain/lib/listing_info.py
- src/datachain/query/dataset.py
- tests/func/test_listing.py
- tests/unit/lib/test_datachain.py
- tests/unit/test_client.py
Refactoring `Client.parse_url()` into two methods:
1. `def parse_url(source: str) -> tuple[StorageURI, str]:` -> just splits `source` into storage uri and relative path and doesn't return `Client` instance any more. 
2. `def get_client(source: str, cache: DataChainCache, **kwargs) -> "Client":` -> returns `Client` instance
This is done because in most of the places we were using old `.parse_url()` to split URL and didn't care about `Client` instance, but because `Client` instance was returned, some additional args like `cache` were needed. 
Now we can use simpler merhod `.parse_url()` where we just need storage uri and path and `.get_client()` where actual `Client` instance is needed
> Refactor `Client.parse_url()`

- src/datachain/lib/arrow.py
- src/datachain/lib/file.py
- tests/unit/lib/test_arrow.py
- tests/unit/lib/test_file.py
> Read arrow files from cache

- src/datachain/lib/tar.py
- src/datachain/lib/webdataset.py
- tests/func/test_datachain.py
- tests/func/test_dataset_query.py
This is a replacement for the deprecated `index_tar()` UDF. Also removes unused `TarStream` class.
Fixes #439
> Add `datachain.lib.tar.process_tar()` generator

- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- src/datachain/query/dataset.py
- tests/func/test_dataset_query.py
Fix for the https://github.com/iterative/studio/issues/10602
In this PR:
- do not generate multiple `join` SQL queries as it could be quite heavy for some warehouse implementations (e.g. ClickHouse, see related PR), if there is `join` (or `union`) found in chain, save results in temporary table and run chain from there. See implementation [here](https://github.com/iterative/datachain/compare/sql-merge-refactoring?expand=1#diff-5cd0b1bd1147a2704c8c333fdb16b0fa21c66e6f5101e4889f7a624d5da4c7cfR916-R935).
- move `join` implementation to warehouse to be able to tweak `join` (e.g. in ClickHouse, see [related PR](https://github.com/iterative/studio/pull/10634))
- [remove](https://github.com/iterative/datachain/compare/sql-merge-refactoring?expand=1#diff-5cd0b1bd1147a2704c8c333fdb16b0fa21c66e6f510 …
> Move 'join' SQL implementation to warehouse

- pyproject.toml
pytest-servers was running on an old (now incompatible) version of Azurite.
Failures shown:
- https://github.com/iterative/datachain/actions/runs/10911782719
- https://github.com/iterative/datachain/actions/runs/10911782712
> update pytest-servers to 0.5.7

- src/datachain/cache.py
- src/datachain/catalog/catalog.py
- src/datachain/client/fsspec.py
- src/datachain/client/local.py
- src/datachain/lib/arrow.py
- src/datachain/lib/file.py
- src/datachain/listing.py
- src/datachain/node.py
- src/datachain/nodes_fetcher.py
- src/datachain/nodes_thread_pool.py
- src/datachain/query/schema.py
- tests/unit/lib/test_file.py
- tests/unit/test_cache.py
* Use `File` instead of `UniqueId` everywhere, replace `Node.as_uid()` with `Node.to_file()`
* Add `File._from_row()` replacing `Catalog._get_row_uid()`
* Transfer `get_hash()` method from `UniqueId` to `File`
* Remove `UniqueId` class and `File.get_uid()`.
* Remove legacy tar handling code
* Split off `File.ensure_cached()` from `File.get_local_path()`
Fixes #36
> Replace `UniqueId` with `File`

- tests/func/test_datachain.py
While investigating #457, I noticed that blindly removing the pre-UDF table logic would pass all existing tests, but not this one (which was removed in #438), even though we have unit-tests that apparently cover it.
> Reintroduce and update test_udf_after_limit()

- tests/examples/test_examples.py
Closes https://github.com/iterative/datachain/issues/462
This PR removes a dud assertion that each example should have some `stderr` output and replaces it with the assertion that each example will have some user-facing output (either stdout or stderr, doesn't matter which). It also removes the reliance on `glob` to order the examples for us.
More discussion can be found in #464
> assert each example has some output instead of stdout and stderr

- pyproject.toml
- src/datachain/__init__.py
- src/datachain/catalog/catalog.py
- src/datachain/cli.py
- src/datachain/error.py
- src/datachain/query/dataset.py
- tests/conftest.py
- tests/func/test_catalog.py
- tests/func/test_datachain.py
- tests/func/test_query.py
- tests/unit/test_query.py
I have also removed mocked tests that were in `test_catalog.py`, and replaced them with unittest that are more simpler and are reduced in scope.
Also, since the `Catalog.query` API is now a generic script runner, I have dropped functional tests as they are heavy and slow, and don't really tests that much. 
I have replaced some `query` test with tests that check what happens if `job_id` is set, etc.
I have kept one test though, for CLI `query` command. I was not sure what to do of it, so I have kept it, but can remove it as I don't have find much return from it.
> query: remove compat for executing last query expression

- src/datachain/catalog/catalog.py
- src/datachain/dataset.py
- src/datachain/error.py
- tests/func/test_dataset_query.py
- tests/func/test_datasets.py
- tests/func/test_pull.py
Currently we are getting some errors that is raised as ValueError in
studio. Capturing all ValueError doesn't seem like a good idea.
So, the exception is specified more properly.
> Introduce DatasetVersionNotFoundError in errors

- .github/workflows/benchmarks.yml
- .github/workflows/release.yml
- .github/workflows/tests-studio.yml
- .github/workflows/tests.yml
- noxfile.py
There is now an official action for `uv`, with support for caching.
See https://github.com/astral-sh/setup-uv.
`uv` also has a "build" frontend, so we can use `uv build` to build package instead of `python-build`.
> use official github action for uv and `uv build`

- src/datachain/catalog/catalog.py
- tests/func/test_catalog.py
`Cattalog.open_object()` is not needed and not used any more.
Also refactoring method to return file signals from row to return actual `File` objects and instead returning always first found file subobject,  now returns file object by name
> Removed `Catalog.open_object()` and refactor method to return file object from row

- tests/unit/test_query.py
> unit.test_query: remove unused `mocker` fixture

- src/datachain/cli.py
- src/datachain/lib/dc.py
- src/datachain/lib/listing.py
- src/datachain/lib/pytorch.py
- src/datachain/query/dataset.py
- tests/func/test_datachain.py
- tests/unit/lib/test_datachain.py
- tests/unit/lib/test_datachain_merge.py
This removes the inheritance of DataChain from DatasetQuery and instead makes the latter an attribute of the former, as suggested in #41.
The de facto public properties and methods `name`, `version`, `session`, `union()`, `count()`, `exec()` and `chunk()` have been explicitly added to `DataChain`.
> Split DatasetQuery from DataChain

- src/datachain/data_storage/sqlite.py
- tests/unit/test_id_generator.py
I found this comment in the code:
```python
```
We have been on v2 of `sqlalchemy` for some time so I have uncommented the previously skipped statement.
> use returning in get_next_ids

- src/datachain/lib/dc.py
- tests/unit/lib/test_datachain.py
This adds a direct `to_csv` function for DataChain to export to CSV (or TSV, etc.) files. This also uses a results iterator and streaming CSV writer, so this should not be limited by memory size, unlike converting the results to pandas then converting to CSV. This has been tested locally and is part of #91
> Adding Streaming CSV Export

- src/datachain/lib/udf.py
AFAICT that obscure feature was introduced in https://github.com/iterative/dvcx/pull/863. It's undocumented (and even contradicts the docs) and untested, so I assume it's unused and broken.
> Don't allow mappers to skip rows

- src/datachain/lib/convert/values_to_tuples.py
- src/datachain/lib/data_model.py
- src/datachain/lib/signal_schema.py
- src/datachain/lib/udf.py
- src/datachain/query/batch.py
- src/datachain/query/dataset.py
- src/datachain/query/dispatch.py
Simplify the logic in `udf.run()` by cleanly separating the 4 different code flows. Part of #40.
> UDF refactoring

- src/datachain/lib/dc.py
- src/datachain/sql/functions/string.py
- src/datachain/sql/sqlite/base.py
- tests/unit/sql/test_string.py
Adds a `replace` function to do something like this:
```python
(
DataChain.from_csv(CROPS_TABLE_PATH, source=False)
.mutate(filepath=string.replace(C("s3_image_url"), "s3://qco-image-data/", "data/"))
)
```
> feat(sqlite): add srtring replace function

- src/datachain/lib/dc.py
- tests/unit/lib/test_datachain.py
Need for customer use case.
In some cases auto-inference fails and we want to enforce the column type.
> add column types to from_csv to override auto inference

- src/datachain/lib/dc.py
- src/datachain/query/__init__.py
- src/datachain/query/schema.py
- tests/unit/lib/test_datachain.py
Fixes issue with a customer scripts, e.g. we do this now and it fails w/o it:
```python
tcrops = tcrops.rename(columns={'source': 'crop_source'}) # Named "crop_source" to avoid "Source" column duplication
```
I think we don't need this anymore.
Closes https://github.com/iterative/dvcx/issues/1583.
> drop DatasetRow outdated class

- src/datachain/catalog/catalog.py
- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- src/datachain/query/session.py
- tests/scripts/feature_class_exception.py
- tests/test_atomicity.py
Refactoring upon the changes at #494 from the comments, this introduces the way to allow a way to persist dataset even if exception is thrown. With this change, the cleanup is now done at the active context. So, we can use the session context as checkpoints now.  Example implementation is as: 
https://github.com/iterative/datachain/blob/029e677e596c84bb8c2ecb56603d164adde03fe8/tests/scripts/feature_class_exception.py#L1-L34
In this file, `local_test_datachain` should only persist since it is the only dataset where the exception doesn't occur in current context. 
Closes #500
> Add a way to persist dataset even if exception is thrown

- src/datachain/catalog/catalog.py
- src/datachain/data_storage/warehouse.py
- src/datachain/query/batch.py
- src/datachain/query/dataset.py
- tests/func/test_datasets.py
Related to https://github.com/iterative/datachain/issues/477 and https://github.com/iterative/studio/issues/10635#issuecomment-2381829809 & https://github.com/iterative/studio/issues/10635#issuecomment-2406225017
All the context for this change is in https://github.com/iterative/datachain/issues/477 but the tl;dr is:
This behaviour is currently undocumented, untested and misunderstood. There is no way to support this behaviour with BigQuery and we have to find another way around datasets appearing ordered. One suggestion is to save the order along with the dataset information in the metastore (perhaps save the appropriate select statement as this would be extendable in the future).
> remove ordering by sys.id

- pyproject.toml
- src/datachain/cli.py
- src/datachain/config.py
- src/datachain/studio.py
- src/datachain/utils.py
- tests/conftest.py
- tests/test_cli_studio.py
- tests/unit/test_config.py
Adds a new auth command to datachain that authorizes the datachain with
studio.
Commands added are:
- `datachain studio login`
- `datachain studio logout`
- `datachain studio token`
```sh
Authenticate Datachain with Studio and set the token. Once this token has been properly configured, Datachain will utilize it for seamlessly sharing
datasets and using Studio features from CLI
positional arguments:
{login,logout,token}  Use `Datachain studio CMD --help` to display command-specific help.
login               Authenticate Datachain with Studio host
logout              Logout user from Studio
token               View the token datachain uses to contact Studio
options:
-h, --help            show this help message and exit
--aws-endpoint-url AWS_ENDPOINT_URL
AWS endpoint URL
--anon …
```
> Add studio auth to datachain

- examples/llm_and_nlp/unstructured-embeddings-gen.py
- pyproject.toml
It is just a patch for the example/test. We should revert once https://github.com/Unstructured-IO/unstructured/issues/3730 is merged and released
> patch unstructured embeddings gen example

- src/datachain/lib/dc.py
- tests/conftest.py
- tests/func/test_datachain.py
This adds the ability to export / upload to FSSpec filesystems in `to_csv` and `to_parquet` - such as exporting directly to S3 or Hugging Face. This is done by passing the relevant url path to the export functions, such as:
`chain.to_parquet("s3://dtulga-datachain-test/test.parquet")`
`chain.to_csv("hf://datasets/dtulga/datachain-test/test.csv")`
This has been tested manually with S3 and Hugging Face, as seen here: https://huggingface.co/datasets/dtulga/datachain-test/tree/main This is part of #236 and #370
> Adding FSSpec Export for CSV and Parquet

- src/datachain/cli.py
- src/datachain/studio.py
- tests/test_cli_studio.py
As part of https://github.com/iterative/studio/issues/10774,
this adds a command as below:
```sh
datachain studio team team_name
Set default team to 'team_name' in <PATH>/.datachain/config
```
```sh
datachain studio team team_name --global
Set default team to 'team_name' in /Users/amritghimire/Library/Application Support/datachain/config
```
> Add option to set team in config for studio

- src/datachain/catalog/catalog.py
- src/datachain/cli.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/func/test_ls.py
- tests/func/test_pull.py
- tests/test_cli_studio.py
This fixes the existing studio client to use the configuration from studio login and provides a way to list the datasets available in Studio.
```sh
$ datachain studio datasets
passed_as_argument (v1)
local_test_datachain (v1)
dql-small (v1)
```
```sh
$ datachain studio datasets --team team_name
passed_as_argument (v1)
local_test_datachain (v1)
dql-small (v1)
```
Relates to https://github.com/iterative/studio/issues/10774
> Implement ls-datasets for studio client

- src/datachain/lib/dc.py
- src/datachain/utils.py
- tests/func/test_datachain.py
- tests/unit/lib/test_datachain.py
- tests/unit/test_utils.py
This PR adds the functions `to_json` and `to_jsonl` to export to JSON / JSON lines from DataChain. These functions support remote fsspec filesystems / URLs (such as `s3://`), similar to `to_csv` and `to_parquet`, and implement streaming writing as well, to enable writing data larger than memory. This also adds tests for these functions, tests for the existing `from_json` and `from_jsonl` functions, and tests for both of these on remote filesystems (such as S3).
This has been tested locally and fixes #533
> Adding JSON / JSON Lines Export Support

- src/datachain/lib/arrow.py
- src/datachain/lib/data_model.py
- src/datachain/lib/utils.py
- tests/unit/lib/test_arrow.py
- tests/unit/lib/test_datachain.py
- tests/unit/lib/test_utils.py
Part of the https://github.com/iterative/datachain/issues/481
Fixes a few issue with nested column names. We had before a [function](https://github.com/iterative/datachain/blob/main/src/datachain/lib/arrow.py#L146-L156) that was normalizing the top level schema names in a single place [here](https://github.com/iterative/datachain/blob/main/src/datachain/lib/arrow.py#L131).
It means that if you have a JSON file to parse with `parse_tabular` (yes, it supports JSONs as well), or any other nested structure where we create Pydantic models for nested fields with [`dict_to_data_model`](https://github.com/iterative/datachain/blob/main/src/datachain/lib/data_model.py#L62-L68) we either had a bunch of non-normalized names except for the top level, or we could end up with a syntax error.
E.g. I had …
> fix(parsing): normalize nested column names

- .github/workflows/tests.yml
- examples/llm_and_nlp/hf-dataset-llm-eval.py
- src/datachain/client/hf.py
- src/datachain/lib/arrow.py
Fixes https://github.com/iterative/datachain/issues/554
Need to understand the reason why we didn't have `source` set properly in the first place. @dberenbaum might know better (please share if you remember anything about this).
TODO:
> fix(hf): use proper source when we create a file entry

- src/datachain/lib/dc.py
> clarify semantics in order_by docstring

- src/datachain/lib/dc.py
- src/datachain/lib/hf.py
Minor cleanup in HF integration code.
> chore(hf): remove unused arguments

- tests/examples/test_examples.py
Per https://github.com/iterative/datachain/pull/555#discussion_r1827088410
Run HF test only once since it using actual API, token, etc. It can be expensive + it seems it might be running into some race condition (not sure yet, we can observe and do retries if needed if we see that it is still unstable)
> fix(tests): hf test can be flakey if runs in parallel

- src/datachain/lib/dc.py
- src/datachain/query/dataset.py
- tests/func/test_datachain.py
- tests/func/test_listing.py
- tests/unit/lib/test_datachain.py
Follow up to #518. More specifically [this comment](https://github.com/iterative/datachain/pull/518/files#r1805859400).
> guarantee order if order_by directly precedes collect in a chain

- src/datachain/sql/types.py
- tests/unit/lib/test_signal_schema.py
- tests/unit/test_data_storage.py
Added support for `UInt32` type
> Support for `UInt32`

- .github/workflows/tests-studio.yml
Pointed out by @dreadatour - Clickhouse cloud currently uses version 24.6 so we should too.
> pin version of clickhouse to 24.6 (match clickhouse-cloud)

- pyproject.toml
- src/datachain/cli.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/conftest.py
- tests/func/test_ls.py
- tests/test_cli_e2e.py
- tests/test_cli_studio.py
With this change, the following variation are available to list datasets
instead of `datachain ls-datasets`:
- `datachain datasets --local`
- `datachain datasets --studio`
```
Name             Version
-------------  ---------
jpg_files              1
all_files              1
jpg_png_files          1
png_files              1
02jpg_files            1
```
- `datachain datasets --all` (Default option)
- `datachain datasets --team TEAM_NAME`
- `datachain datasets`
```
Name                       Version  Studio    Local
-----------------------  ---------  --------  -------
jpg_files                        1  ✔         ✔
hello                            2  ✔         ✖
02jpg_files                      1  ✔         ✔
embeddings-and-metadata          1  ✔         ✖
```
By default, if the user has …
> feat(cli): enhance dataset listing with additional options for studio

- src/datachain/lib/dc.py
Add an explicit example on an alternative syntax for `agg` (I spent some time to figure our the appropriate signature).
> doc(agg): add an example with custom UDF spec

- src/datachain/catalog/catalog.py
- src/datachain/data_storage/metastore.py
- src/datachain/dataset.py
- src/datachain/lib/dataset_info.py
- tests/conftest.py
- tests/func/test_datasets.py
- tests/func/test_pull.py
We needed unique identified of specific dataset, as name + version is not strong enough. User can remove dataset and re-create it with the same name + version.
This is needed in scenarios like pulling dataset from remote where we need to check if dataset already exists in user's local DB where it can be named differently or have different version, but it's the same dataset regardless.
> Adding `uuid` to dataset version

- src/datachain/data_storage/sqlite.py
- tests/func/test_dataset_query.py
This PR fixes `offset` method for DatasetQuery/DataChain for SQLite warehouse (it works fine in SaaS).
+ added tests (fail before fix: https://github.com/iterative/datachain/actions/runs/11829848002)
> Fix 'limit' + 'offset' methods for SQLite warehouse

- src/datachain/toolkit/__init__.py
- src/datachain/toolkit/split.py
- tests/conftest.py
- tests/func/test_toolkit.py
See related issue, docstrings and tests.
```python
from datachain import DataChain
from datachain.toolkit import train_test_split
dc = DataChain.from_storage("s3://bucket/dir/")
train, test = train_test_split(dc, [0.7, 0.3])
train.save("dataset_train")
test.save("dataset_test")
```
```python
train, test, val = train_test_split(dc, [0.7, 0.2, 0.1])
train.save("dataset_train")
test.save("dataset_test")
val.save("dataset_val")
```
- `seed`
- `shuffle`
> Split Dataset into train/test/val

- src/datachain/sql/sqlite/types.py
- tests/unit/sql/sqlite/test_types.py
Fix for dumping np array into SQLite as current json lib doesn't work well with the object type np arrays
> Fixing np array dumping

- src/datachain/asyn.py
Fixes the hanging issue when trying to cancel or close the script.
The test on #521 hangs. This is because we run the producer on a separate `ThreadPoolExecutor` in a _loop_.
https://github.com/iterative/datachain/blob/9fd31553d9003c09e135d8b4a2345ced4ffc5bdd/src/datachain/asyn.py#L64-L70
https://github.com/iterative/datachain/blob/9fd31553d9003c09e135d8b4a2345ced4ffc5bdd/src/datachain/asyn.py#L165-L166
When the interpreter shuts down, `ThreadPoolExecutor` waits for all threads to `join()`. Since `produce()` is still running, `join()` hangs indefinitely.
Although the script hangs on other platforms too, you might notice that the CI failed only on the Windows tests on #521.
This is because [`test_query_e2e`](https://github.com/iterative/datachain/blob/ba9c5819f7f3ee578c8c55866463069f0e10d30 …
> asyncmapper: shutdown producer on generator close

- src/datachain/asyn.py
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- src/datachain/lib/settings.py
- src/datachain/lib/udf.py
- src/datachain/query/dataset.py
- tests/func/test_datachain.py
- tests/scripts/name_len_slow.py
- tests/unit/test_asyn.py
This adds a `prefetch` setting which enables async downloading of objects to the cache before running a generator or mapper UDF (see #40). The default is to use 2 workers, but it can be disabled using `.setting(prefetch=0)`. Note that it has no effect if caching isn't enabled (caching is disabled by default).
In order for this to work, `AbstractWarehouse.dataset_select_paginated()` is now required to be thread-safe, so query result pages are now buffered as a list in that function.
> Implement pre-fetching in map() and gen()

- src/datachain/lib/arrow.py
- src/datachain/lib/data_model.py
- src/datachain/lib/dc.py
- src/datachain/lib/hf.py
- src/datachain/lib/utils.py
- tests/unit/lib/test_arrow.py
- tests/unit/lib/test_datachain.py
- tests/unit/lib/test_hf.py
Adds `schema_sample_size` option to `explode` to specify how many samples it should be analyzing do derive schema. This is needed in case some fields are missing in a single sample.
Fixes a few other things to make it work on the existing fixture.
> feat(dc): make expand work if some fields are optional

- src/datachain/query/dataset.py
- src/datachain/sql/sqlite/base.py
- tests/test_query_e2e.py
The PR makes three changes:
1) The E2E test is updated only to send the interrupt signal once (done in the first commit).
2) Suppresses `usearch`'s `UserWarning`, and
3) Fixes "leaked semaphore issue" (see #615) due to worker process being SIGKILL'd on `KeyboardInterrupt`. 
This happens because, while running script, sending <kbd>Ctrl</kbd> + <kbd>C</kbd> would also send SIGINT to
the worker processes, but then [it would immediately follow up with a SIKILL][1] [after 0.25s][2].
This allowed very little time for workers to do cleanup, due to which, Python was raising `UserWarning`
for leaked semaphores:
```py
.../lib/python3.12/site-packages/multiprocess/resource_tracker.py:257: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean >
```
Also see …
> test_query_e2e: do not interrupt running script multiple times

- src/datachain/data_storage/sqlite.py
- tests/unit/test_database_engine.py
This fixes an issue where `db._connect()` would fail to preserve the original database file when it wasn’t explicitly specified. The root cause involved external directory changes on `read_meta()` which uses [`datamodel-codegenerator` that briefly changes the current working directory][1].
Since we were not storing original `db_file`, the `db.clone()` would try to open the database file from the new working directory, instead of the original one, which disrupted the database connection to the background thread running for the prefetch.
By saving the `db_file`, `clone()` can now reliably reuse the correct database uri/path, avoiding unintended connections to a different database file.
CI failure: https://github.com/iterative/datachain/actions/runs/11991835481/job/33430946078#step:8:128 …
> sqlitedb: retain `db_file` in `_connect` method to ensure proper connection on `db.clone()`

- src/datachain/data_storage/warehouse.py
Let's see if the test passes.
Context: https://github.com/iterative/datachain/pull/521#discussion_r1857724246.
> dataset_select_paginated: do not clone on each paginated query

- src/datachain/lib/dataset_info.py
- src/datachain/lib/webdataset_laion.py
- src/datachain/model/bbox.py
- src/datachain/model/pose.py
- src/datachain/model/segment.py
It seems like the newest release of Pydantic expects type-safe defaults to be provided (failure [here](https://github.com/iterative/datachain/actions/runs/12040183868/job/33569570076))
> fix type issues produced by new version of pydantic

- src/datachain/catalog/catalog.py
- src/datachain/data_storage/metastore.py
- src/datachain/dataset.py
- src/datachain/lib/dataset_info.py
- tests/func/test_catalog.py
Related to https://github.com/iterative/studio/issues/10849 and replaces https://github.com/iterative/datachain/pull/628 (see replaced PR for some details)
This PR adds `DatasetListRecord` and `DatasetListVersion` `dataclass`es and uses those classes within `Catalog`'s `ls_datasets` and `list_datasets_versions` methods. Using these new classes means that we can significantly cut down the data being processed when listing datasets. This should give us a performance boost in both the CLI and SaaS and hopefully prevent the slow query alerts in the related issue.
Note: There is some duplication added in this PR, it does not seem practical to extend the original `dataclass`es in this instance.
> add DatasetListRecord and DatasetListVersion dataclasses to only extract required fields when listing datasets

- src/datachain/dataset.py
- tests/unit/test_dataset.py
This PR ensures that we don't load a dataset version's preview to a dict from a string until it has been requested. This should mean that we can continue to use the pattern of loading all version for a dataset via `catalog.get_dataset` without taking the performance hit of loading all of the dataset version previews via `json.loads`
> do not pre-load dataset version preview from string

- src/datachain/dataset.py
Reverting to using json.loads for the dataset version preview because orjson cannot cope with some custom serialization that we do (demonstrated [here](https://github.com/iterative/studio/actions/runs/12078410076/job/33682779597?pr=11000)).
We can revisit this but for now I don't want to leave Studio in a broken state.
> do not use orjson to parse dataset version preview

- src/datachain/cli.py
- tests/test_cli_e2e.py
- tests/test_cli_studio.py
The changes for the cli commands:
- `datachain datasets ls` from `datachain ls-datasets`
- `datachain datasets edit` from `datachain edit-datasets`
- `datachain datasets rm` from `datachain rm-datasets`
- `datachain datasets pull` from `datachain pull`
Closes https://github.com/iterative/datachain/issues/576
> Refactor the cli commands for the datasets

- src/datachain/func/__init__.py
- src/datachain/func/func.py
- tests/unit/lib/test_datachain.py
Follow-up for the https://github.com/iterative/datachain/pull/649
This will allow us to run:
```python
from datachain import C, DataChain, func
(
DataChain.from_values(name=["foo", "bar", "baz"], anxiety=[0.0, 1.0, 0.5], boredom=[0.7, 0.0, 0.05])
.group_by(
anxiety=func.sum(func.case((C("anxiety") > 0.1, 1), else_=0)),
boredom=func.sum(func.case((C("boredom") > 0.1, 1), else_=0)),
)
.show()
)
```
Instead of:
```python
from datachain import C, DataChain, func
from sqlalchemy import case
(
DataChain.from_values(name=["foo", "bar", "baz"], anxiety=[0.0, 1.0, 0.5], boredom=[0.7, 0.0, 0.05])
.mutate(
anxiety=case((C("anxiety") > 0.1, 1), else_=0),
boredom=case((C("boredom") > 0.1, 1), else_=0),
)
.group_by(
anxiety=func.sum("anxiety"),
boredom=func.sum("boredom"),
)
.show()
)
```
> Support 'case' operator inside functions

- tests/unit/lib/test_datachain.py
Follow-up for the https://github.com/iterative/datachain/pull/649
> Add test for 'group_dy' without 'partition_by'

- src/datachain/lib/dc.py
- src/datachain/lib/pytorch.py
This should enable prefetching on `to_pytorch` API. We were not passing any `settings` to the `DataChain` instances created inside `to_pytorch`, due to which it was not using `cache` or `prefetch`.
I have refrained from setting `workers`, etc. because I believe that is better left to `PytorchDataLoader` for now. 
I have found this PR to increase performance for `torch-loader.py` example by 20-25% when prefetch and cache is enabled. However, this was done on my machine and was not a scientific measurement.
Closes #631.
> pytorch dataset: pass cache/prefetch to DataChain instances

- examples/llm_and_nlp/hf-dataset-llm-eval.py
This might be a fix for example running in CI [failure](https://github.com/iterative/datachain/actions/runs/12021069833/job/33887783578?pr=626).
Error is:
```
429 Client Error: Too Many Requests for url: https://api-inference.huggingface.co/models/meta-llama/Llama-3.1-70B-Instruct/v1/chat/completions (Request ID: uDQ_4laxVhlqgTqG73hOX)
```
On the other hand we also do have this error in logs:
```
Model requires a Pro subscription; check out hf.co/pricing to learn more. Make sure to include your HF token in your query.
```
Same time CI run in this PR is successful so I hope this will do the trick.
> Use 'setup' in HuggingFace llm example

- src/datachain/lib/pytorch.py
#653 did not really enable prefetching. Prefetch was only implemented for `map()`, so the example gave me a false impression that the prefetching was working, but it was not.
Now, `to_pytorch` uses `AsyncMapper` to prefetch the data. The number of workers is set to 2 by default, but it can be changed by setting the `prefetch` in the settings.
For me, this dropped the time to download the data by 90%, from ~300s to now ~35s.
Closes #631.
> `to_pytorch`: enable prefetching

- src/datachain/data_storage/metastore.py
- tests/func/test_catalog.py
Related to https://github.com/iterative/studio/issues/7008 & https://github.com/iterative/studio/pull/11057
By ordering the query result for list_datasets we fix a couple of downstream problems.
> order datasets and versions in list_datasets query

- src/datachain/func/__init__.py
- src/datachain/func/numeric.py
- src/datachain/func/string.py
- src/datachain/sql/functions/numeric.py
- src/datachain/sql/functions/string.py
- src/datachain/sql/sqlite/base.py
- tests/unit/test_func.py
New `bit_hamming_distance` function will allow us to calculate [hamming distance](https://en.wikipedia.org/wiki/Hamming_distance) between to numbers. This will be useful on image deduplication (see [this article](https://fullstackml.com/wavelet-image-hash-in-python-3504fdd282b5) for more details).
Also added `byte_hamming_distance` function, just because it is similar and it is worth it to add in the same PR 👀
> Add 'bit_hamming_distance' and 'byte_hamming_distance' SQLite functions

- .github/workflows/tests.yml
Delightful self-plagiarism from https://datachain.ai/blog/testing-external-contributions-using-github-actions-secrets
> Allow testing external contributions using secrets

- src/datachain/lib/signal_schema.py
- tests/unit/lib/test_signal_schema.py
See original issue with full example: https://github.com/iterative/datachain/issues/637
Also fix for the https://github.com/iterative/studio/issues/10989
---
Let's say we have a complex model with other models used as signals:
```python
from datachain.model.ultralytics import YoloBBoxes, YoloPoses, YoloSegments
class MyYolo(DataModel):
bbox: YoloBBoxes
segm: YoloSegments
poses: YoloPoses
```
this PR allow us to use these sub-signals in `mutate` (assuming `yolo` is signal with `MyYolo` type):
```python
dc.mutate(my_poses=C("yolo.poses"))
```
then `my_poses` will be a signal with `YoloPoses` type.
> Allow adding new signal from existing signal field

- docs/examples.md
Replace `'` to `"` in `docs/examples.md`
> Fix a typo in `docs/examples.md`

- docs/contributing.md
- docs/css/github-permalink-style.css
- docs/examples.md
- docs/index.md
- docs/quick-start.md
- docs/references/index.md
- docs/tutorials.md
- mkdocs.yml
- Remove icon from site title
- Use GH style link icon for headers
- Use left sidebar only for `API References`
> chore: follow up docs navigation update

- .github/workflows/tests.yml
This commit introduces a check step that acts as a single point of failure for specified jobs in a workflow. The step fails if any of the specified jobs fail and passes only if they succeed. This is useful for adding a single step to "Required Checks" for PR.
This avoids the need to manually add each job to "Required Checks", and reduces maintenance overhead when renaming jobs.
> ci: add a consolidated `check` step for required PR checks

- .github/workflows/tests.yml
- tests/examples/test_examples.py
GHA only provides 5 concurrent macOS jobs for a team. Running 8 macOS jobs for "examples" (for a single PR) is excessive, and frankly unnecessary here, since they are more or less covered in `ubuntu-latest`.
This makes us wait a lot of time before the PR succeeds, especially when GHA is overloaded.
> ci: drop macos example test run

- examples/get_started/torch-loader.py
- src/datachain/lib/pytorch.py
PytorchDataset creates a tqdm instance internally. Since pytorch's DataLoader can open multiple instances of the Dataset in multiple worker processes (1 in each process), it can mess up output, and make it look very busy/noisy.
`DataLoader` is _iterable_, and returns batches of data. So, `tqdm`, if needed, should be used by anyone who consumes `DataLoader`. The example has been adjusted to show the usage.
Also, the existing tqdm progress bar reads more like a debug log message than to show actual progress.
> PytorchDataset: remove internal tqdm progress bar

- src/datachain/client/__init__.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- src/datachain/lib/meta_formats.py
- src/datachain/query/dataset.py
This PR halves the total startuptime from 2.8s to 1.4s, with minimal effort.
There are two more imports that can be reduced: requests, and numpy, that will reduce total time by .3 sec.
The total import time spent is now 1.251s. It's difficult to fix remaining imports because we expose them on top-level imports, and fixing them will require too much duplication/effort or incur runtime costs.
The import trace looks like follows after this PR:
> cli: improve startup time

- src/datachain/cli.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/test_cli_studio.py
This introduces a cancel job operation for CLI that can be used to
cancel a job running in studio.
Command:
`datachain studio cancel <JOB_ID`
> Implement cancel job operation for CLI

- src/datachain/catalog/catalog.py
- src/datachain/cli.py
- tests/func/test_pull.py
Replacing `no_cp` with `cp` argument in `Catalog.pull_dataset()` and setting it to `False`, meaning we won't cp / instantiate dataset files when pulling it from Studio. If use want's to do instantiation, it needs to explicitly set `cp` flag to `True` now.
> Making `cp` as non default when pulling dataset

- examples/get_started/json-csv-reader.py
- src/datachain/lib/dc.py
- src/datachain/lib/meta_formats.py
- tests/func/test_datachain.py
- tests/func/test_meta_formats.py
- tests/unit/lib/test_datachain.py
I don't think methods like `print_json_schema` belong to the main DC API.
It drops methods:
`print_json_schema` (a helper `gen_datamodel_code` can be used)
`print_jsonl_schema` (`format` can be specified `jsonl` in the `gen_datamodel_code`)
`from_jsonl` (`format` can be specified to `jsonl`)
It drops args:
`print_schema` (it is weird to have top level API just to toggle a single print. logger or something else should be used)
It renames args:
`meta_type` -> `format` (similar to some other places).
There will be more changes to all this JSON logic.
Tutorial to be fixed:
https://colab.research.google.com/github/iterative/datachain-examples/blob/main/formats/json-metadata-tutorial.ipynb
> cleanup a few from_json methods from DC

- src/datachain/lib/dc.py
- tests/func/test_catalog.py
- tests/unit/test_listing.py
Partially addresses and stabilizes https://github.com/iterative/datachain/issues/725
Fixes a few situations in the way we find and suggest an existing cached listing when we do an `update=True`.
```python
listing = sorted(listings, key=lambda ls: len(ls.name))[0]
```
This code actually was picking the "biggest" one instead. There should have been `reverse=True`.
So, in a situation like:
`file:///whatever/dir1` exists and cached
`file:///whatever/` exists and cached
and we were trying to update the `file:///whatever/dir1` - it was updating the `file:///whatever/` instead.
`file:///whatever/` exists and cached
`file:///whatever/dir1` doesn't yet exist
and we do "update=True" for the `file:///whatever/dir1`
it was updating the whole `file:///whatever/` which can be arbitrary large. And we …
> fix(listing): pick exact or create new one on update

- src/datachain/query/dataset.py
- src/datachain/query/session.py
- tests/func/test_session.py
As found during debugging this use case https://github.com/iterative/datachain/issues/724 - it's better to keep already cached listing, otherwise some small operations become slow to iterate until you fully sure that script is running, and the script on every run does the same indexing, every single time. There is no reason for that to my mind.
> fix(session): keep cached successful listings

- src/datachain/catalog/catalog.py
- src/datachain/lib/dc.py
- src/datachain/lib/listing.py
- tests/unit/test_listing.py
Moves `parse_uri` out of public DC methods + renames it a bit to make move obvious hopefully.
> fix(dc): move parse uri and rename out of main class

- docs/quick-start.md
1. New mistral lib does not pick up env variable by default - fix.
2. With new async enabled it hits to mistral limit very often - remove parallel and cache. It also simplifies the code!
> Fix Mistral example in quick-start

- docs/quick-start.md
Otherwise, the 2nd example does not work
> quick-start: A small note about transformers install

- src/datachain/lib/arrow.py
- src/datachain/lib/dc.py
- tests/unit/lib/test_arrow.py
Alternative proposal to #744, that uses a `ReferenceFileSystem` (which acts as a pointer) to preserve partitioned information.
> from_parquet: use virtual filesystem to preserve partition information when using cache

- src/datachain/client/gcs.py
- tests/unit/test_client_gcs.py
When retrieving URL for file in GCP bucket if this bucket is public and we have no GCP credentials set, error will be raised.
In this PR we are returning public download URL in this case instead of exception.
Note: I think we need to do the same for other types of storages.
> Return url for file in GCP public bucket instead of error

- src/datachain/query/session.py
We're supposed to accept empty session names as per the documentation string and as per the surrounding logic, but the regular expression was broken.
> Allow empty session name

- src/datachain/catalog/catalog.py
- src/datachain/catalog/datasource.py
- src/datachain/client/fsspec.py
- src/datachain/dataset.py
- src/datachain/lib/dc.py
- src/datachain/lib/listing.py
- src/datachain/listing.py
- src/datachain/node.py
- tests/func/test_catalog.py
- tests/func/test_datachain.py
- tests/unit/test_listing.py
Adjusts `from_storage` to avoid creating a listing / or using a listing cache when we need a single file. In this case we are creating a single entry DC right away.
This speedups a lot simple cases when you need a single file from a repo and it stars indexing all files around. It won't do this again.
Also, it won't be failing by hitting the previously cached index when we just write and then read a single file.
> fix(from_storage): no listing / cache on a single file

- src/datachain/cache.py
- src/datachain/client/fsspec.py
- src/datachain/client/gcs.py
- src/datachain/client/local.py
- tests/func/test_catalog.py
- tests/func/test_pull.py
On top of https://github.com/iterative/datachain/pull/734
Fixes versioning. So far it seems it was broken when we were trying to download a previous version of a file from version aware fs.
This is breaking basic examples of versioning with DataChain.
> fix(cache, client): support versioned files

- src/datachain/client/fsspec.py
- src/datachain/lib/file.py
In Storage `Client` abstract class we do have `info_to_file` method. All it implementation have `path` param, but in abstract class this is `parent` param. This PR is going to fix this error.
> Fix Storage abstract Client 'info_to_file' signature

- src/datachain/lib/arrow.py
- src/datachain/lib/dc.py
- tests/unit/lib/test_arrow.py
- tests/unit/lib/test_datachain.py
The last less critical item from https://github.com/iterative/datachain/issues/725. 
Closes #725
If there is no file, before we were getting: 
`datachain.lib.dc.DatasetPrepareError: Dataset processing prepare error: Must provide at least one schema to unify.`
on a query like this: 
`dataset_chain = DataChain.from_parquet("file.parquet")` if `file.parquet` doesn't exist
now we are getting:
`datachain.lib.dc.DatasetPrepareError: Dataset processing prepare error: no files to parse.`
- Add test
> fix: better message if no files passed on parse tabular

- src/datachain/lib/listing.py
Fixes https://github.com/iterative/datachain/issues/762 
We override `fsspec`'s `info` to also analyze if an object listed / returned is a special case of a file like this: https://cloud.google.com/storage/docs/objects#simulated-folders
> fix(listing): ignore special 'dir' files

- src/datachain/cli.py
- src/datachain/studio.py
- tests/test_cli_e2e.py
- tests/test_cli_studio.py
With this change, the jobs related commands are as:
- `datachain job run`
- `datachain job cancel`
- `datachain job logs`
[![asciicast](https://asciinema.org/a/XbgQ8Pa3tEEn0GtFSs01TNOXc.svg)](https://asciinema.org/a/XbgQ8Pa3tEEn0GtFSs01TNOXc)
[![asciicast](https://asciinema.org/a/9AAbWkEBm2ESiT58zyaqogECO.svg)](https://asciinema.org/a/9AAbWkEBm2ESiT58zyaqogECO)
With this, we can wrapup the [#10774](https://github.com/iterative/studio/issues/10774)
Closes [#10774](https://github.com/iterative/studio/issues/10774)
> Move jobs related commands under jobs and introduce logs

- .github/workflows/tests.yml
There are 5 computer vision and 4 llm and nlp examples under test. It makes sense to split these into separate groups now.
Run times from https://github.com/iterative/datachain/actions/runs/12623540854/job/35172643534?pr=781 - 
```
292.75s call     tests/examples/test_examples.py::test_computer_vision_examples[examples/computer_vision/iptc_exif_xmp_lib.py]
276.43s call     tests/examples/test_examples.py::test_llm_and_nlp_examples[examples/llm_and_nlp/unstructured-embeddings-gen.py]
104.46s call     tests/examples/test_examples.py::test_computer_vision_examples[examples/computer_vision/openimage-detect.py]
56.33s call     tests/examples/test_examples.py::test_llm_and_nlp_examples[examples/llm_and_nlp/unstructured-summary-map.py]
42.42s call …
```
> split out testing of computer vision from llm and nlp examples in CI

- pyproject.toml
LLM and NLP tests have been broken on Windows by the most recent `unstructured` release (what a surprise). This PR restricts the version to `<0.16.12`. Seems like a better option than #785
> add max bound for unstructured package (broken on Windows)

- src/datachain/client/fsspec.py
Implementing file upload.
Usage example:
```python
import io
from typing import Iterator
import imageio
import imageio.v3 as iio
from ultralytics import YOLO
from datachain import DataChain, File
from datachain.catalog import get_catalog
from datachain.client import Client
from datachain.model.ultralytics import YoloPoses
def pose_estimation(client: Client, yolo: YOLO, file: File) -> Iterator[tuple[File, int, float, YoloPoses]]:
stem = file.get_file_stem()
ext = file.get_file_ext()
reader = imageio.get_reader(io.BytesIO(file.read()), format=ext)
fps = reader.get_meta_data()["fps"]
for frame, img in enumerate(reader):
filename = f"{stem}_{frame:06d}.jpg"
img_encoded = iio.imwrite("<bytes>", img, extension=".jpeg")
f = client.upload(filename, img_encoded)
timestamp = frame / fps
results = …
```
> File upload

- src/datachain/lib/signal_schema.py
- tests/unit/lib/test_signal_schema.py
Fixes https://github.com/iterative/studio/issues/11140 (private repo).
If we have a class hierarchy: 
```python
from typing import Iterator
from datachain import DataChain, File
dc = DataChain.from_storage("gs://mybucket")
class VideoInterval(File):
start: int
end: int
def get_actions(file: File) -> Iterator[VideoInterval]:
yield VideoInterval(start=6, end=15, **file.model_dump())
yield VideoInterval(start=39, end=51, **file.model_dump())
yield VideoInterval(start=145, end=166, **file.model_dump())
dc = dc.gen(action=get_actions).save("res")
```
We want for the `VideoInterval` class to have enough information about its base class `File` to be available after we serialize  / deserialize it. For downstream tools to be able to work with it like a `File` (e.g. preview in Studio).
Also, this …
> feat(signal schema): serialize base classes for custom types

- examples/computer_vision/ultralytics-bbox.py
- examples/computer_vision/ultralytics-pose.py
- examples/computer_vision/ultralytics-segment.py
This PR disables the Yolo progress bars for the following computer vision examples:
- ultralytics-bbox
- ultralytics-pose
- ultralytics-segment
The main reason for doing this is keeping spam out of the examples output. Without the change the output for the bbox examples looks like this:
```console
❯ python examples/computer_vision/ultralytics-bbox.py                                                                                                        ✘ INT  .env 08:48:29
Preparing: 20 rows [00:00, 14503.13 rows/s]
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ …
```
> turn off Yolo progress bars in ultralytics examples

- .gitignore
When running the `ultralytics` examples files like `yolo11n-seg.pt` are produced in the root directory. I have come close to committing these a couple of times.
> git ignore files all pytorch files

- examples/get_started/torch-loader.py
- src/datachain/cache.py
- src/datachain/catalog/catalog.py
- src/datachain/client/azure.py
- src/datachain/client/fsspec.py
- src/datachain/client/gcs.py
- src/datachain/client/s3.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/arrow.py
- src/datachain/lib/hf.py
- src/datachain/listing.py
- src/datachain/query/dataset.py
related to https://github.com/iterative/datachain/issues/723
This PR removes completed progress bars from DataChain's console output. This gives us a quick way to quieten down the output for "quick commands"
https://github.com/user-attachments/assets/a01b638d-065a-426c-ad51-6f5aec96227f
https://github.com/user-attachments/assets/cff1d02d-806c-4c91-b1e6-8d7477265e89
> do not persist completed progress bars

- src/datachain/query/dataset.py
- tests/unit/lib/test_datachain.py
Code like this:
```python
video_dc = (
video_dc
.limit(1)
.map(video=lambda file: add_video_metadata(file), output={'video': Video})
.map(video=lambda file: add_video_metadata(file), output={'video': Video})
)
```
ignores or rewrites the `video`,
additional mapper: 
```python
video_dc = (
video_dc
.limit(1)
.map(video=lambda file: add_video_metadata(file), output={'video': Video})
.map(video=lambda file: add_video_metadata(file), output={'video': Video})
.map(video=lambda file: add_video_metadata(file), output={'video': Video})
)
```
breaks it with an obscure error:
```python
File "/Users/ivan/Projects/dvcx/.venv/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 1324, in _set_parent_with_dispatch
self._set_parent(parent, **kw)
File …
```
> fix(map): don't allow rewriting existing columns

- src/datachain/func/__init__.py
- src/datachain/func/conditional.py
- tests/unit/sql/test_conditional.py
- tests/unit/test_func.py
This PR implements `ifelse` function uses already implemented `case` function.
Example of usage:
```python
dc.mutate(
res=func.ifelse(C("num") > 0, "P", "N"),
)
```
> Implements if else function

- src/datachain/data_storage/db_engine.py
- src/datachain/data_storage/schema.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- tests/func/test_datachain.py
Fixes #660 
Refactors `DataTable` by removing direct access to sqlachemy (and thus requiring direct access to sa.Engine, etc). This allows us to do a check and reconnect if connection was already closed.
> fix(schema): reconnect closed connection

- src/datachain/client/s3.py
Until (or similar fix) lands https://github.com/fsspec/s3fs/pull/929 we need to do this check to make DataChain work with custom endpoints provided via env vars (e.g. in Studio).
> fix(client): disable bucket cache if region or endpoint are specified

- src/datachain/cache.py
- src/datachain/catalog/catalog.py
- src/datachain/client/azure.py
- src/datachain/client/fsspec.py
- src/datachain/client/gcs.py
- src/datachain/client/s3.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/arrow.py
- src/datachain/lib/hf.py
- src/datachain/listing.py
- src/datachain/progress.py
- src/datachain/query/dataset.py
Partially addresses #780 
https://github.com/user-attachments/assets/911f8bff-502c-411c-aa7b-90e9e3778e6e
What I don't know how to fix yet is progress bars when we use `parallel` and we run the whole thing in the subprocess. In this case child process doesn't have access to Ipython widgets (or whatever the mechanics is behind these nice progress bars).
> Import tqdm to support jupyter better

- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- tests/unit/lib/test_file.py
Closes #807.
```python
dc.export_files("output_dir", link_type="symlink")
```
> file: support exporting files as a symlink

- src/datachain/lib/dc.py
- src/datachain/lib/pytorch.py
- src/datachain/lib/udf.py
- src/datachain/query/dataset.py
- tests/benchmarks/test_datachain.py
- tests/func/test_datachain.py
- tests/func/test_pytorch.py
- tests/unit/test_pytorch.py
This PR removes the prefetched item after use in the UDF. This is enabled by default on `prefetch>0`, unless `cache=True` is set in the UDF, in which case the prefetched item is not removed.
For pytorch dataset, this is not enabled by default, but can be enabled by setting `remove_prefetched=True` in the `PytorchDataset` class. This is done so because the dataset can be used in multiple epochs, and removing the prefetched item after use can cause it to redownload again in the next epoch.
The exposed `remove_prefetched=True|False` setting could be renamed to
some better option. Feedbacks are welcome.
(I think the UX around prefetch needs to be improved and made obvious).
> prefetching: remove prefetched item after use in udf

- src/datachain/lib/arrow.py
There is a bug in `fsspec==2024.12.0` that causes the `ReferenceFileSystem` to incorrectly make `fs._open` return a coroutine object instead of a file-like object. (See a proposed PR to fix this issue: fsspec/filesystem_spec#1769.)
We have a test for the expected behavior ([`test_arrow_generator_partitioned` in `tests/unit/lib/test_arrow.py`](https://github.com/iterative/datachain/blob/aad99e2eab48513387bc187d9196084614012f2b/tests/unit/lib/test_arrow.py#L111-L112)) running in the CI environment.
But that does not fail because the latest version of `fsspec` does not get installed in the CI due to the upper limit set by the `datasets` library.
The `datasets` library is only installed as part of the `hf` and `tests` extras, so the default installation of `datachain` will encounter this …
> ReferenceFileSystem: use fs.open instead of fs._open

- src/datachain/sql/sqlite/base.py
If `usearch` fails to download the extension, it will keep retrying in the future. This adds significant cost - for example, in `tests/func/test_pytorch.py` run, it was invoked 111 times, taking ~30 seconds in total.
This PR caches the return value for the whole session.
Review with [`?w=1`](https://github.com/iterative/datachain/pull/833/files?w=1) for better diff. :)
> memoize usearch.sqlite_path()

- pyproject.toml
- tests/func/test_pytorch.py
This is achieved by:
1. reducing the number of images in the fake dataset from 1000 to 100,
2. removing tokenizer from open_clip_torch, to a fake one, and,
3. disabling cache and prefetch in the `fake_dataset` fixture. The fixture does not use the files, and `PytorchDataset` reopens the dataset, so there is no need to cache or prefetch the data.
With this, the runtime for `tests/func/test_pytorch.py` is reduced from ~80s to <8s on my machine.
> tests: reduce pytorch functional tests' runtime

- pyproject.toml
- Reverts iterative/datachain#838
- It was downgraded to fix https://github.com/iterative/datachain/issues/690
- Let's use the old version for now and feel free to close the PR if dependent-bot to stop them from recreating
> Revert "build(deps): bump mkdocs-material from 9.5.22 to 9.5.50"

- .github/workflows/tests.yml
- tests/scripts/name_len_slow.py
[The `test_query_e2e` takes almost ~8mins to run][1] (whole CI job takes 11 mins). The `name_len_slow` script is the main culprit, since it sleeps for 1 sec in each udf function and that mapper is run in a single process parallel mode.
```
474.21s call     tests/test_query_e2e.py::test_query_e2e@tmpfile
```
This commit adds a limit of 3 files to the name_len_slow script, which is enough, since it's only running a single process.
(We immediately interrupt the running process after seeing "UDF Processing Started" gets printed).
This also split tests into two: one for the e2e tests and one for the rest, so that these things are more obvious in the future.
[1]: https://github.com/iterative/datachain/actions/runs/12879531971/job/35907168617#step:8:82
> e2e tests: limit name_len_slow to 3, split e2e tests from others

- .github/workflows/tests.yml
The current setup with `pull_request_target` is unnecessary because tests are skipped when tokens are unavailable.
This currently affects HuggingFace-related tests.
Maintainers can help when the contributor's change affects those areas. This situation is no different from other tests that require `ANTHROPIC_API_KEY` or `OPENAPI_KEY`, or Studio tests that don't run in fork.
Using `pull_request_target` also prevents changes to workflows from being tested, as it always runs workflows from the default branch. This makes it difficult to modify workflows.
Switching to `pull_request` resolves this issue.
Also, see https://github.com/iterative/datachain/pull/667#issuecomment-2527821664.
> ci: switch trigger from `pull_request_target` to `pull_request`

- .github/workflows/tests.yml
Docs are here: https://pytest-cov.readthedocs.io/en/latest/readme.html#coverage-data-file
See change from #842 -https://app.codecov.io/gh/iterative/datachain/commit/7d0913e37a31f42704ba24a1e602193f58f99b0e
> append e2e tests coverage instead of overwriting

- src/datachain/client/fsspec.py
- src/datachain/lib/file.py
- tests/func/test_file.py
Closes #771
The original example https://github.com/iterative/datachain/pull/758 from becomes:
```python
import io
from collections.abc import Iterator
import imageio
import imageio.v3 as iio
from ultralytics import YOLO
from datachain import DataChain, File
from datachain.model.ultralytics import YoloPoses
base_path = "gs://redacted"
def pose_estimation(
yolo: YOLO, file: File
) -> Iterator[tuple[File, int, float, YoloPoses]]:
stem = file.get_file_stem()
ext = file.get_file_ext()
reader = imageio.get_reader(io.BytesIO(file.read()), format=ext)
fps = reader.get_meta_data()["fps"]
for frame, img in enumerate(reader):
filename = f"{base_path}/frames/{stem}_{frame:06d}.jpg"
img_encoded = iio.imwrite("<bytes>", img, extension=".jpeg")
f = File.upload(filename, img_encoded)
timestamp = frame / …
```
> add upload classmethod to File

- src/datachain/dataset.py
- src/datachain/lib/listing.py
- tests/func/test_catalog.py
- tests/func/test_datachain.py
- tests/func/test_datasets.py
- tests/func/test_listing.py
The parsing utility should not hit remote servers at all. Also returning `None` does not make sense for `parse_listing_uri` when the uri is a file since there is no listing.
It's better to keep this function naive than to add other logic into it. And I think `get_listing` is a better place for that, to have all kinds of logic with side-effects.
The only other place where this function is used besides `get_listing` is in `DatasetDependency.dataset_name`. In that case, a dataset already exists and since there can be no listing for a file uri, it's safe to assume that the uri is either a glob or a directory path.
https://github.com/iterative/datachain/blob/e45a62f43cad47a162345f01e3a2f9a1fff8f47a/src/datachain/dataset.py#L94
I stumbled upon this when I was investigating why a unit-test was …
> pull `_is_file` checks to `get_listing`

- examples/llm_and_nlp/hf-dataset-llm-eval.py
Patching the error shown here: https://github.com/iterative/datachain/actions/runs/12888313233/job/35932939032
Failed here too: https://github.com/iterative/datachain/actions/runs/12899335202/job/35967939172?pr=850
> catch HfHubHTTPError in hf-dataset-llm-eval example

- src/datachain/lib/listing.py
With this change, we will return the ClientError without any extra error
or logs in the terminal. As a result, if we capture the ClientError in
the script, we will have minimum output.
Example query:
```python
from datachain.error import ClientError
from datachain.lib.dc import C, DataChain
try:
wds = (
DataChain.from_storage("az://amrit-datachain-test/shards")
.filter(C.name.glob("00000000.tar"))
.settings(parallel=8, cache=True)
)
wds.show()
except ClientError as e:
print(str(e))
print("Exception caught")
```
Before changes:
```
Traceback (most recent call last):                                                                                                                           
File "/Users/amritghimire/Documents/coding/iterative/datachain/.venv/lib/python3.12/site-packages/adlfs/s …
```
> Filter logging to hide massive stacktrace for access issue

- src/datachain/client/fsspec.py
- src/datachain/lib/file.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/func/test_file.py
This PR changes the `upload` methods to have data (from) first and then path (to) second as input parameters.
> rearrange input params for upload methods

- src/datachain/lib/dc.py
- src/datachain/lib/listing.py
- tests/unit/test_func.py
Adding ability to do something like: 
```python
dc = dc.mutate(val=0.5)
```
This will create column `val` with constant value `0.5` for all rows.
For now it's implement for basic primitives like `int`, `bool`, `str` and `float`. Later on we can extend it to things like lists etc.
> Added ability for constant literals in `DataChain.mutate(...)`

- src/datachain/catalog/catalog.py
- tests/func/test_pull.py
Related to https://github.com/iterative/studio/issues/11283
We call Studio to get the stats for a particular dataset version but we've already retrieved the same information in an earlier call. This PR removes the dataset stats call from pull.
> do not call stats in ds pull (from Studio)

- src/datachain/func/conditional.py
- src/datachain/func/func.py
- tests/unit/test_func.py
Up until now we only allowed python primitives as case values like str, int, float ...
With this PR we will allow columns as well (note that this also adds ability for columns as outcomes in `ifelse` as it uses `case` under the hood ), e.g
```python
res = dc.mutate(test=case((C("num") < 3, C("val")), else_="default"))
res = dc.mutate(test=ifelse(C("num") < 3, C("val"), "default"))
```
> Added columns as case values

- examples/get_started/common_sql_functions.py
- src/datachain/func/__init__.py
- src/datachain/func/array.py
- src/datachain/sql/functions/array.py
- src/datachain/sql/sqlite/base.py
- src/datachain/sql/sqlite/types.py
- tests/unit/sql/test_array.py
- tests/unit/test_func.py
Adds:
`chain.filter(array.contains("emd", 1.0)).show()`
to be used in queries like:
```python
embeddings = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
chain = DataChain.from_values(emd=embeddings).save("embeddings")
chain.filter(array.contains("emd", 1.0)).show()
```
> add arrays contains function

- docs/references/index.md
Follow-up for the https://github.com/iterative/datachain/pull/885
> Could you add a link to to [Overview page](https://docs.datachain.ai/references/) as well?
> Add toolkit link to API Reference index page

- pyproject.toml
`build docs` is currently failing for all platforms in the CI against Python 3.9. This PR follows the provided error message.
example: https://github.com/iterative/datachain/actions/runs/13126453256/job/36623622317
> add eval-type-backport for docs built with python 3.9

- src/datachain/func/__init__.py
- src/datachain/func/conditional.py
- tests/unit/sql/test_conditional.py
- tests/unit/test_func.py
It's possible to use `|` for OR expressions, but  sometimes it's just more handy to have explicit `or_` function, just like sqlalchemy has.
> Adding explicit `or_` function

- src/datachain/cli/__init__.py
- src/datachain/cli/commands/datasets.py
- src/datachain/cli/parser/__init__.py
- src/datachain/dataset.py
- tests/test_cli_e2e.py
- tests/test_cli_studio.py
This changes the way the datasets are listed in a CLI.
| Before | After |
|---|----|
|![before](https://github.com/user-attachments/assets/597f8fc1-5c33-40c7-8c84-c17556bb5cdb)|![after](https://github.com/user-attachments/assets/630ccd54-4b86-417e-a55c-fe7452ef5cec)|
|![before](https://github.com/user-attachments/assets/b4a07e65-5135-4b94-9e56-c8ebfb7bc498)|![after](https://github.com/user-attachments/assets/d4a0df60-7549-4886-a970-469ec4680895)|
|![before](https://github.com/user-attachments/assets/715c3b5f-bdeb-44cf-b9db-80b387c200d1)|![after](https://github.com/user-attachments/assets/405bcd66-c242-4577-a476-907a00ee74f3)|
New option:
-------
Closes https://github.com/iterative/studio/issues/11280
> Improve datachain ds ls output

- src/datachain/cli/__init__.py
- src/datachain/cli/commands/datasets.py
- src/datachain/cli/parser/__init__.py
- src/datachain/studio.py
- tests/conftest.py
- tests/test_cli_studio.py
With this change, a optional positional arg is added for datachain ds
ls.
Example output:
```
datachain ds ls temp
Name    Studio    Local
------  --------  -------
temp    v1        ✖
temp    v2        ✖
temp    v3        ✖
temp    v4        ✖
temp    v5        ✖
temp    v6        ✖
temp    v7        ✖
temp    v8        ✖
temp    v9        ✖
temp    v10       ✖
temp    v11       ✖
temp    v12       ✖
temp    v13       v13
```
> Add datasets filter for `datachain ds ls`

- src/datachain/catalog/catalog.py
- src/datachain/studio.py
- tests/func/test_pull.py
Instead of:
```
(.venv) √ Projects/cattle-care-train % datachain ds pull ds://something
Error: Error from server: Dataset something not found
```
we now do:
```
(.venv) √ Projects/cattle-care-train % datachain ds pull ds://something
Error: Dataset something not found
```
I think this should be enough
> fix(cli): remove extra Error from the message

- src/datachain/remote/studio.py
- src/datachain/utils.py
W/o this fix, if team is not set via env variable `DVC_STUDIO_TEAM` and / or DataChain config, `self.team` in Studio remote client raises a `DataChainError` (which is fine). What is not fine is that `_send_request` keeps retying with an exponential backoff on those.
Pretty much means that first time someone is trying to run something like `datachain ds pull ...` there are big chances to hit a long hang w/o any messages at all. Then if you are like to wait you can see that it just expect team to be set.
Also improves the messaging around `get_team` errors a bit.
> fix(cli, studio): don't retry on non request/http errors

- src/datachain/func/__init__.py
- src/datachain/func/conditional.py
- tests/unit/sql/test_conditional.py
- tests/unit/test_func.py
It's possible to use `&` for AND expressions, but  sometimes it's just more handy to have explicit `and_` function, just like sqlalchemy has.
Also we already have explicit `or_`
> Adding explicit `and_` function

- noxfile.py
Closes #906.
> Running tests without the `--cov` option is significantly faster on Python 3.12. Similarly,  the tests run quite fast on Python 3.11 with or without `--cov`.
>
> It turns out that this slowdown is caused by `pytest-cov`, which happens due to a regression in CPython 3.12, see:
>
>- https://github.com/python/cpython/issues/107674
>- https://github.com/nedbat/coveragepy/issues/1665
>
>It took me a lot of time to figure out why, because this did not show up on profiling, just that everything was 3x - 4x slower. And profilers do tend to add significant overhead, so I ignored it initially.
>
>With `pytest-cov`, the specific test is already running quite close to ~5s timeout, that the newer dependencies that `datamodel-code-generator` brought were enough to increase that to >5s, …
> set `COVERAGE_CORE=sysmon` to improve tests' performance in 3.12

- README.rst
- docs/quick-start.md
- src/datachain/client/fsspec.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- tests/conftest.py
- tests/func/test_cloud_transfer.py
- tests/func/test_datachain.py
This renames the export files to to storage adding the support for the
cloud destinations as well.
With this change, the following code will work:
```py
from datachain.lib.dc import DataChain
ds = DataChain.from_storage("az://amrit-test-az/image.png")
ds.save("az")
ds.to_storage("gs://amrit-datachain-test/destination", placement="filename")
```
Closes #859
> Rename export_files to to_storage with cloud support

- src/datachain/lib/dc.py
- src/datachain/query/session.py
- tests/func/test_datachain.py
This adds a new argument named client_config for from_storage call for DataChain.
Usage:
```py
chain = DataChain.from_storage(
"s3://my-bucket/my-dir",
client_config = {"aws_endpoint_url": "<minio-endpoint-url>"}
)
```
Closes #911
> Add option to pass client config to from_storage

- src/datachain/cli/__init__.py
- src/datachain/cli/commands/show.py
- src/datachain/cli/parser/utils.py
- src/datachain/lib/data_model.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- src/datachain/lib/signal_schema.py
- src/datachain/utils.py
- tests/func/test_hidden_field.py
- tests/unit/lib/test_signal_schema.py
For any hidden fields, a `_hidden_fields` class variable will hide the
fields from the values when showing using `dc.show`.
Example on how to hide fields for custom model:
```python
from datachain import DataModel, DataChain
class InnerClass(DataModel):
inner_value: float
hide_inner: float
_hidden_fields = ["hide_inner"]
class OuterClass(DataModel):
outer_value: float
hide_outer: float
inner_object: InnerClass
_hidden_fields = ["hide_outer"]
inner = InnerClass(inner_value=1.1, hide_inner=1.2)
outer = OuterClass(outer_value=1.3, hide_outer=1.4, inner_object=inner)
DataChain.from_values(
outer=[outer],
nums=[1]
).show()
```
This also takes care when we display the datachain using following command:
```
datachain show az
```
Similarly, https://github.com/iterative/studio/pull/11357 takes …
> Add option to specify the hidden field

- src/datachain/func/__init__.py
Noticed that we don't see `func.path` operations in docs and users can't directly use those functions.
> fix(file): expose file operations to func module

- src/datachain/lib/video.py
In this PR there is a fix for `too many open files` error during video fragments/frames upload.
For every new uploaded file we are initializing new catalog and creating new connection to SQLite DB:
```
$ lsof -p 15463
Python  15463 vlad    0u      CHR               16,2 0t12628660                3211 /dev/ttys002
Python  15463 vlad    1u      CHR               16,2 0t12628660                3211 /dev/ttys002
Python  15463 vlad    2u      CHR               16,2 0t12628660                3211 /dev/ttys002
...
Python  15463 vlad   22u      REG               1,17  220061696           104546080 /Users/vlad/work/iterative/playground/.datachain/db
Python  15463 vlad   23u      REG               1,17      16512           111515250 /Users/vlad/work/iterative/playground/.datachain/db-wal
Python …
```
> Fix 'too many open files' error during video upload

- docs/examples.md
> docs(examples): remove imports from datachain.lib.dc in examples

- .github/workflows/tests.yml
- pyproject.toml
- src/datachain/client/fsspec.py
- src/datachain/client/hf.py
- src/datachain/lib/file.py
This commit wraps the HfFileSystem class to convert to an async filesystem. This is done by using the `AsyncFileSystemWrapper` class from the `fsspec` library, which requires `fsspec>=2024.12.0`. 
With the wrapper, all the functions will run in a separate thread in an executor, and won't block the main event-loop.
This will now support all the async APIs that the `Client` expects and, hence, will support file caching.
The alternative here is to have two different implementations, one async and another sync, but that is too much of an effort at this time for huggingface.
Fixes #661.
> fix(huggingface): wrap HfFileSystem to an async filesystem

- .github/workflows/tests.yml
Reverts iterative/datachain#942.
It looks like the issue has been fixed with https://github.com/AnimMouse/setup-ffmpeg/releases/tag/v1.2.1, and hasn't happened since then.
https://github.com/iterative/datachain/actions/runs/13779766244/job/38535781568
https://github.com/iterative/datachain/actions/runs/13779766244/job/38535781253
We can revert this if it happens in the future again.
> Revert "Fix ffmpeg setup in GitHub CI"

- src/datachain/client/fsspec.py
- src/datachain/client/local.py
- src/datachain/lib/listing.py
- tests/func/test_client.py
- tests/func/test_ls.py
- tests/utils.py
fsspec does not support this at all, and I don't think it's important for us to support this.
The goal here is to simplify and remove manual parsing of paths as much as possible.
Related: https://github.com/iterative/dvcx/pull/402
> refactor(client): drop support for uppercased scheme URLs

- src/datachain/error.py
- src/datachain/fs/utils.py
- src/datachain/lib/listing.py
- src/datachain/utils.py
- Reraises any exception as `ClientError` in `datachain.lib.listing.get_listing` when checking if a path is a directory. This helps us remove the imports of two libraries, `gcsfs` and `botocore`  which reduces import time: #947.
- Move `isfile` to `datachain.fs.utils`.
- Remove unused utilities from `datachain.utils`
> refactor(listing): reraise any exception as ClientError on `isdir` check

- src/datachain/catalog/loader.py
`datachain.sql.sqlite.setup()` runs on import of this module. That takes more than 750ms on my machine.
https://github.com/iterative/datachain/blob/4d4d4298434f0ba7836a0d9b52f68e1955a531cd/src/datachain/data_storage/sqlite.py#L57
After this PR, the total importtime drops to <600ms.
Related: #947.
> lazily import from `datachain.data_storage.sqlite`

- src/datachain/catalog/catalog.py
- src/datachain/catalog/loader.py
- src/datachain/cli/__init__.py
- src/datachain/data_storage/warehouse.py
- src/datachain/func/func.py
- src/datachain/lib/dc.py
- src/datachain/lib/file.py
- src/datachain/lib/listing.py
- src/datachain/query/dataset.py
Overall, this now reduces the total import time to <400ms.
```fish
for i in (seq 10)
python -c 'import timeit; print(timeit.timeit("import datachain", number=1))'
end
```
```
0.39508233399828896
0.37911972802248783
0.383127932989737
0.37568117599585094
0.37784146700869314
0.37930534698534757
0.3757595890201628
0.3764792810252402
0.38182323198998347
0.37827736599138007
```
> make some imports lazy

- tests/test_import_time.py
Part of https://github.com/iterative/datachain/issues/947.
Taken an inspiration from https://github.com/pola-rs/polars/blob/63acc86ef657f1b404355ee8b6d4ed9786a8ed1a/py-polars/tests/unit/test_polars_import.py.
> tests: add an unit test for catching import time regressions in the future

- .github/workflows/tests.yml
- noxfile.py
- pyproject.toml
- tests/test_import_time.py
This commit disables coverage for the test_import_time test to avoid unpredictable results. The import usually takes  ~400ms but with coverage enabled, it was frequently going past 600ms on my machine.
Which I believe is also happening on the CI.
- Also added a log message to display the full contents of the output from `-Ximporttime` in case of a parse error in `from_csv`.
Thanks to @dreadatour for noticing this issue. Fixes #974.
> fix(tests): disable coverage in test_import_time

- src/datachain/cli/commands/ls.py
There is a bug with `ls` CLI command: because of `tqdm` output starts not from the beginning of the line.
I wish I can find a better fix related to `tqdm`, but I can not find any in decent amount of time :(
Using list instead of iterator looks like a reasonable temporary fix, since output of `ls` command should not be huge.
**Note**: may be related to https://github.com/iterative/datachain/issues/780
```
$ datachain ls
gs://datachain-demo/50k-laion-files/000000/@v1
gs://datachain-demo/dogs-and-cats/@v1
gs://datachain-demo/dogs-and-cats/@v2
gs://datachain-demo/dogs-and-cats/@v3
gs://datachain-demo/dogs-and-cats/@v4
gs://datachain-demo/open-images-v6/@v1
```
```
$ datachain ls
gs://datachain-demo/50k-laion-files/000000/@v1
gs://datachain-demo/dogs-and-cats/@v1 …
```
> Fix output of 'ls' CLI command

- examples/llm_and_nlp/hf-dataset-llm-eval.py
- src/datachain/lib/dc.py
- src/datachain/lib/meta_formats.py
- src/datachain/lib/signal_schema.py
- src/datachain/lib/udf.py
- src/datachain/lib/udf_signature.py
- tests/func/test_datachain.py
- tests/unit/lib/test_datachain_bootstrap.py
- tests/unit/lib/test_signal_schema.py
- tests/unit/lib/test_udf_signature.py
- tests/unit/sql/test_array.py
Follow-up for the https://github.com/iterative/datachain/pull/966
See this thread for more details: https://github.com/iterative/datachain/pull/966#discussion_r1994190977
We are now checking types of UDF arguments if they are defined. Also there is a special case for `File` signal: it will be automatically converted to `TextFile`, `ImageFile` or `VideoFile` if one of these types are used in UDF. See also my comments about implementation and examples below 🙏
Let's say we have Dataset `my-ds` with two signals: `name: str` and `value: int`.
We can now define UDF to process these signals, e.g.:
```python
def process(name: str, value: int) -> float:
return len(name) / value
DataChain.from_dataset("my-ds").map(signal=process)
```
In this PR we are adding type checking for UDF param types based …
> Check UDF params types in SignalSchema

- src/datachain/lib/dc.py
- src/datachain/lib/signal_schema.py
- tests/unit/lib/test_datachain.py
This is a quick and dirty implementation to display `__repr__` for `DataChain` instances. The implementation uses `DataChain.print_schema()` method to capture the output and return it.
This makes working in the REPL and notebooks easier. PTAL at the tests for the output.
Also note that I changed the default indentation to `2` from `4` before. I think less indentation makes it easier on REPL to work with.
And also fixed a small bug in `SignalSchema.print_tree` that was always indenting the schema by at least a single space.
```py
>>> from datachain import DataChain
>>> dc = DataChain.from_values(col1=["a", "b", "c"])
>>> dc
col1: str
>>> dc.select_except("col1")
Empty DataChain
>>> dc.map(col2=lambda col1: col1 * 2)
col1: str
col2: str
```
> feat(dc): add repr to show schema for DataChain instances

- src/datachain/diff/__init__.py
- tests/unit/lib/test_diff.py
There was an issue when `right_on` was used in `DataChain.diff()` which is fixed in this PR. Test case is added as well.
Note that "root" of the issue were column values for rows for `DELETED` status in final diff result. Problem is that for diff we take schema from left chain (the one on which we call `.diff()`) but values from the right, as the row is removed in the left. Since left and right can have different schemas, it's impossible to take correct values from the right so in this PR we just take those column values on which matching was done. So if someone did:
```python
diff = left.diff(right, on=["source", "path"], deleted=True, status_col="diff")
```
rows with `D` status would have `source` and `path` filled with values, and all other columns would be set to DB default (`NULL` …
> Fixing `DataChain.diff()` when `right_on` is used

- tests/func/test_datachain.py
When multiple workers are running, we don't have access to all the worker's standard error output through `captured.err` and can't see the `KeyboardInterrupt` exception name; this only works when we schedule the task to the first worker, which runs locally and allows capturing its output.
See https://github.com/iterative/studio/pull/11439#discussion_r2009089748
> Fix test_udf_distributed_interrupt with multiple workers

- docs/examples.md
- docs/quick-start.md
- docs/references/data-types/file.md
- docs/references/data-types/imagefile.md
- docs/references/data-types/textfile.md
- docs/references/data-types/videofile.md
- docs/references/datachain.md
- src/datachain/__init__.py
- src/datachain/lib/dc/__init__.py
- src/datachain/lib/dc/csv.py
- src/datachain/lib/dc/datachain.py
- src/datachain/lib/dc/datasets.py
- src/datachain/lib/dc/hf.py
- src/datachain/lib/dc/json.py
- src/datachain/lib/dc/listings.py
- src/datachain/lib/dc/pandas.py
- src/datachain/lib/dc/parquet.py
- src/datachain/lib/dc/records.py
- src/datachain/lib/dc/storage.py
- src/datachain/lib/dc/utils.py
- src/datachain/lib/dc/values.py
- tests/scripts/feature_class.py
- tests/scripts/feature_class_parallel.py
- tests/scripts/feature_class_parallel_data_model.py
- tests/scripts/name_len_slow.py
- Updated import statements to use `import datachain as dc` for consistency across examples and documentation.
- Refactored example code snippets in `examples.md` and `quick-start.md` to reflect the new import style.
- Enhanced documentation in `datachain.md`, `file.md`, `imagefile.md`, `textfile.md`, and `videofile.md` to clarify usage of `from_storage` and other methods.
- Introduced new utility functions in `dc` module for CSV, JSON, and other data formats to streamline data ingestion processes.
- Added new methods for handling datasets and listings, improving the overall functionality of the DataChain library.
Closes #984
> Introduce functional datachain API

- pyproject.toml
Requires bumping `setuptools` to 77.0.0 or later.
See:
- [PEP 639](https://peps.python.org/pep-0639)
- [Writing pyproject.toml - license](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license)
> pyproject: update license to PEP 639 format

- src/datachain/client/fsspec.py
- src/datachain/lib/dc/json.py
- src/datachain/lib/dc/storage.py
- tests/func/test_datachain.py
- Updated the `from_storage` function to accept a list of URIs, allowing for batch processing of storage locations.
- Introduced a new internal function `_extract_chain` to streamline the extraction of data from individual URIs.
- Enhanced documentation to clarify usage and added examples for multiple URIs.
- Improved caching logic to avoid redundant updates for URIs pointing to the same storage location.
This change increases the flexibility and efficiency of data retrieval
in the DataChain library.
> Enhance `from_storage` function to support multiple URIs

- pyproject.toml
With recent release in pydantic, the pickling is not working as
expected. This restricts the pydantic to 2.10.6 untill we fix the
breaking changes.
Relevant links:
- https://github.com/pydantic/pydantic/releases/tag/v2.11.0
- https://github.com/pydantic/pydantic/pull/11032
- https://iterativeai.slack.com/archives/C04A9RWEZBN/p1743143098907759
> Restrict pydantic less that 2.11 to fix CI

- src/datachain/lib/dataset_info.py
- src/datachain/lib/dc/datasets.py
- src/datachain/query/session.py
- tests/func/test_datachain.py
- tests/unit/test_session.py
Fixing `dc.datasets().show()` not to show temp datasets.
> Fix to not show temp datasets

- src/datachain/lib/udf.py
- src/datachain/query/dispatch.py
While processing distributed UDF we need not only `processed` rows callback, but also callbacks for `downloaded` and `generated` rows. In this PR we make it possible to use this callback in SaaS UDF distributor.
See related Studio PR: https://github.com/iterative/studio/pull/11467
> Add callbacks for 'downloaded' and 'generated' rows while processing distributed UDF

- src/datachain/lib/signal_schema.py
- tests/unit/lib/test_datachain.py
- tests/unit/lib/test_signal_schema.py
Splitting error messages when signal is not found and when trying to remove nested signal which is not supported.
Also making error message little bit better.
> Better error hadling in `.select_except()`

- README.rst
- docs/quick-start.md
- examples/get_started/json-csv-reader.py
- src/datachain/catalog/catalog.py
- src/datachain/data_storage/schema.py
- src/datachain/data_storage/sqlite.py
- src/datachain/data_storage/warehouse.py
- src/datachain/lib/dc/csv.py
- src/datachain/lib/dc/datachain.py
- src/datachain/lib/dc/hf.py
- src/datachain/lib/dc/json.py
- src/datachain/lib/dc/listings.py
- src/datachain/lib/dc/pandas.py
- src/datachain/lib/dc/parquet.py
- src/datachain/lib/dc/storage.py
- src/datachain/lib/dc/values.py
- src/datachain/lib/listing.py
- src/datachain/listing.py
- tests/func/test_data_storage.py
- tests/unit/lib/test_datachain.py
- tests/unit/test_listing.py
This PR is a follow up of https://github.com/iterative/datachain/pull/1012
Idea is to rename all public appearance of `object_name` to `column`
> Renaming `object_name` to `column`

- examples/multimodal/wds_filtered.py
- src/datachain/lib/dc/datachain.py
- tests/func/test_catalog.py
- tests/func/test_datachain.py
- tests/func/test_hidden_field.py
- tests/unit/lib/test_datachain.py
Added new method to create temp datasets `.persist()`. Old way to create temp datasets was to call `.save()` without name but now name is mandatory in `.save()`.
> Added `DataChain.persist()`

- tests/test_import_time.py
This test fails too often :(
Latest example: https://github.com/iterative/datachain/actions/runs/14176251298/job/39711770663
Will be happy to have better option and also will be happy to discuss this.
> Increase MAX_IMPORT_TIME_MS in tests up to 800ms

- src/datachain/catalog/loader.py
- src/datachain/query/dataset.py
- src/datachain/query/dispatch.py
- tests/unit/test_catalog_loader.py
Add `DATACHAIN_DISTRIBUTED_PYTHONPATH` env variable to be able to set `PYTHONPATH` for the `DATACHAIN_DISTRIBUTED` module.
Not useful right now, but will be used later in the follow-up distributed compute updates.
> Add DATACHAIN_DISTRIBUTED_PYTHONPATH env variable

- src/datachain/catalog/catalog.py
- src/datachain/cli/__init__.py
- src/datachain/cli/commands/datasets.py
- src/datachain/cli/commands/show.py
- src/datachain/cli/parser/__init__.py
- src/datachain/data_storage/metastore.py
- src/datachain/dataset.py
- src/datachain/lib/dataset_info.py
- src/datachain/lib/dc/datachain.py
- src/datachain/lib/dc/datasets.py
- src/datachain/query/dataset.py
- src/datachain/remote/studio.py
- src/datachain/studio.py
- tests/conftest.py
- tests/func/test_datachain.py
- tests/func/test_datasets.py
- tests/func/test_pull.py
- tests/test_cli_studio.py
- tests/unit/lib/test_datachain.py
Renaming `labels` to `attrs` in dataset model and related methods / functions.
Also added ability to filter datasets in `dc.datasets()` by attributes.
Attributes can be just normal name e.g `NLP` or combination of name and value e.g `location=US`. Examples of attribute filters are:
* `NLP` -> search all datasets that have `NLP` attribute value
* `location=US` -> search all datasets that have `location=US` attribute (combination of name and value)
* `location=*` -> search all datasets that have `location` name and any value .. e.g `location=US`, `location=UK` etc.
Note that for now filtering logic is implemented in application level. Ideal solution would be to implement it in DB level and for the users to use `.filter()` methods with functions, but that will be done as follow-up later on.
> Renamed dataset `labels` to `attrs` and added attributes filters in `dc.datasets()`

- src/datachain/lib/convert/values_to_tuples.py
- src/datachain/lib/dc/records.py
- src/datachain/lib/signal_schema.py
- src/datachain/query/dataset.py
- src/datachain/query/schema.py
- tests/func/test_read_database.py
This is a partial revert of e201aefaf9 from #1034, which added support for inferring schema with `Optional[T]` types, and also added support for creating nullable columns in the database.
Also, this commit sets the default value for a given column if the value is `None` which depends on a given dialect/database. For example, for SQLite, the default value for a `String` column is `None`, while for ClickHouse, it is an empty string.
Support for nullable columns can be added separately in the future.
> read_database/read_records: set default for the column instead of null

- docs/commands/auth/login.md
- docs/commands/auth/logout.md
- docs/commands/auth/team.md
- docs/commands/auth/token.md
- docs/commands/index.md
- docs/commands/job/cancel.md
- docs/commands/job/logs.md
- docs/commands/job/run.md
- mkdocs.yml
Since authentication and jobs are only commands that are exposed in
datachain help as below, this adds a section for jobs and auth flow for
cli.
> feat(docs): add CLI reference section with authentication and job management commands

- pyproject.toml
With latest pyarrow [20.0.0](https://github.com/apache/arrow/releases/tag/apache-arrow-20.0.0) release we now have tests broken.
<details>
<summary>pytest run output</summary>
$ pytest tests/unit/lib/test_hf.py -k test_hf_array
Test session starts (platform: darwin, Python 3.13.2, pytest 8.3.5, pytest-sugar 1.0.0)
benchmark: 5.1.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/vlad/work/iterative/datachain
configfile: pyproject.toml
plugins: servers-0.5.10, cov-6.0.0, hypothesis-6.129.4, sugar-1.0.0, benchmark-5.1.0, mock-3.14.0, xdist-3.6.1, requests-mock-1.12.1
collected 6 items / 5 deselected / 1 selected …
> Limit pyarrow version to be <20.0.0

- noxfile.py
- pyproject.toml
- src/datachain/lib/dc/values.py
TODO: we also should check all other `dc.read_xxx` methods
> Set name for 'read_values' UDF

- src/datachain/data_storage/metastore.py
- tests/unit/lib/test_datachain.py
This fixes dataset version preview update which was broken after we introduced semver because we used wrong syntax for SQLAlchemy `where` condition which resulting only one condition in `AND` to be in the final query which at the end resulted on updating all versions preview with latest one. 
It was (accidentally) working before probably because version column was `int`
> Fixing dataset version preview update

- src/datachain/query/session.py
Caught an error:
```
$ python index.py
Exception ignored in atexit callback <function Session._global_cleanup at 0x1058b76a0>:
Traceback (most recent call last):
File ".../python3.13/site-packages/datachain/query/session.py", line 198, in _global_cleanup
if isinstance(obj, Session):  # Cleanup temp dataset for session variables.
ReferenceError: weakly-referenced object no longer exists
```
While running this simplest script:
```python
import datachain as dc
dc.read_storage("s3://bucket/", anon=True).save("dataset")
```
> Fix session cleanup

- examples/incremental_processing/delta.py
- examples/incremental_processing/utils.py
- tests/examples/test_examples.py
Adds an example of delta (incremental) processing.
> add incremental processing example

- .github/codecov.yaml
- .github/workflows/tests.yml
While code coverage is very important metric and we should work on increasing this as much as possible, it is not really useful to see CI build failed status in `main` branch if only code coverage fails.
Trying to solve this issue:
Not sure if this will helps, need to test it.
> Do not fail CI in main branch if only codecov fails

- src/datachain/catalog/catalog.py
- src/datachain/dataset.py
- src/datachain/lib/listing.py
- src/datachain/remote/studio.py
- tests/func/test_catalog.py
- tests/func/test_datachain.py
- tests/func/test_dataset_query.py
- tests/func/test_datasets.py
- tests/func/test_listing.py
Optimize listing:
- if we know storage name: pass it as prefix
- do not fetch jobs as we only need them for datasets
> Listing refactoring and optimizations

- src/datachain/model/ultralytics/bbox.py
- src/datachain/model/ultralytics/pose.py
- src/datachain/model/ultralytics/segment.py
- tests/func/model/test_yolo.py
Fixes issue on prod: 
```
Error while waiting for UDF d1add18f-9e34-4c31-a4ac-03108bcdebfb: Pose3D must be a dictionary with coordinates.
```
probably in new Utlralytics we can get None as keypoints when we have some bounding boxes returned.
This code:
```
def pose_estimation(yolo: YOLO, file: VideoFile) -> Iterator[tuple[VideoFrame, ImageFile, YoloPoses]]:
for frame in file.get_frames(step=10):
image = frame.save("gs://datachain-cattle-care/frames")
results = yolo(image.read())
yield frame, image, YoloPoses.from_results(results)
```
> fix(video): append models only if they exist

- src/datachain/client/azure.py
- src/datachain/client/gcs.py
- src/datachain/client/s3.py
- tests/func/test_client.py
Attempt to fix https://github.com/iterative/datachain/issues/1120
I didn't find a reasonable explanation for having this logic (except that some old code similar `found=True/False` logic, but in that case I think the dir name itself was returning (?))
> Fix empty bucket index

- docs/references/remotes.md
Reference discussion: https://iterativeai.slack.com/archives/C04A9RWEZBN/p1748811798250819
> Change the default value to true for version aware in docs

- src/datachain/client/azure.py
- src/datachain/client/fsspec.py
- src/datachain/client/gcs.py
- src/datachain/client/s3.py
- tests/func/test_listing.py
Fixing a few issue where even setting `version_aware=False` was not enough to force it not use Version APIs + do all the version id related checks.
We now don't fetch `version_id` field in commands like `read_storage` for the Files if `version_aware` False is passed. Column value will be None and we won't be enforcing or using `version_id` downstream (e.g. in prefetch, etc).
To make code like this:
```python
datachain.read_storage("s3://ivan-test-versioned", client_config={"version_aware": False}, update=True).show(10, include_hidden=True)
datachain.read_csv("s3://ivan-test-versioned/test.json", client_config={"version_aware": False}, update=True).show(10)
```
work w/o additional permissions:
```
s3:ListBucketVersions
s3:GetObjectVersion
```
(and the same should be for the GCS and Azure) …
> fix(client): avoid version ids if version aware is false

- src/datachain/lib/file.py
- src/datachain/lib/image.py
- src/datachain/lib/utils.py
- src/datachain/lib/video.py
Fix for https://github.com/iterative/datachain/issues/1125
```
File "/Users/vlad/.virtualenvs/datachain/lib/python3.13/site-packages/multiprocess/queues.py", line 138, in get_nowait
return self.get(False)
~~~~~~~~^^^^^^^
File "/Users/vlad/.virtualenvs/datachain/lib/python3.13/site-packages/multiprocess/queues.py", line 125, in get
return _ForkingPickler.loads(res)
~~~~~~~~~~~~~~~~~~~~~^^^^^
File "/Users/vlad/.virtualenvs/datachain/lib/python3.13/site-packages/dill/_dill.py", line 303, in loads
return load(file, ignore, **kwds)
File "/Users/vlad/.virtualenvs/datachain/lib/python3.13/site-packages/dill/_dill.py", line 289, in load
return Unpickler(file, ignore=ignore, **kwds).load()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File …
```
> Fix pickle/unpickle FileError exception

- src/datachain/semver.py
- tests/unit/test_semver.py
To compare versions we calculating `int` based on semver.
Before it was `major * 100 + minor * 10 + patch` — max supported version is `9.9.9` (versions like `0.0.10` and `0.1.0` are the same for this algorythm).
In this PR it will be `major * 1_000_000_000_000 + minor * 1_0000_000 + patch` (max supported version is `999999.999999.999999`).
Also added more test cases.
> Fix datachain version comparison

- src/datachain/client/hf.py
W/o this we are getting `RuntimeError("Loop is not running")` from the `sync()` wrapper:
```python
if loop is None or loop.is_closed():
raise RuntimeError("Loop is not running")
```
`loop` is None since we have this piece of in the `AsyncFileSystem` `init`:
```python
if not asynchronous:
self._loop = loop or get_loop()
else:
self._loop = None
```
and `asynchronous` flag is set in the `AsyncWrapper` this way:
```python
if asynchronous is None:
asynchronous = running_async()
```
So `running_async()` async defines if loop is created or not. And if it is not creted, `sync` doesn't work. In Jupyter `running_async()` returns True. So, all our code that does `sync` is breaking`. I'm not sure if there is a better fix for all of this tbh. cc @skshetry @martindurant
If this sounds reasonable, we …
> fix(hf): init with async set to false to always init loop

- src/datachain/lib/arrow.py
- tests/unit/lib/test_arrow.py
In case we have empty column in CSV file we want to process, this error happens:
```
TypeError: DataType(null) datatypes not supported, column: column_name
```
We are using string as default type for columns, let's use it here too.
**TODO:**
> Use string type for null-columns in CSV

- src/datachain/catalog/catalog.py
Fixes issues with pulling Studio datasets:
```python
import datachain as dc
dataset = dc.read_dataset("@shcheklein.default.test_dataset", update=True)
```
Triggering:
```python
Traceback (most recent call last):
File "/Users/ivan/Projects/datachain/test.py", line 4, in <module>
dataset = dc.read_dataset("@eldada-brainspace.default.parquet-processed-ecg", update=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ivan/Projects/datachain/src/datachain/lib/dc/datasets.py", line 186, in read_dataset
query = DatasetQuery(
^^^^^^^^^^^^^
File "/Users/ivan/Projects/datachain/src/datachain/query/dataset.py", line 1142, in __init__
self.catalog.get_dataset_with_remote_fallback(
File "/Users/ivan/Projects/datachain/src/datachain/catalog/catalog.py", …
```
> trust Studio names, don't validate locally

- .gitignore
- examples/multimodal/audio-to-text.py
- pyproject.toml
- src/datachain/__init__.py
- src/datachain/lib/audio.py
- src/datachain/lib/file.py
- src/datachain/lib/udf.py
- tests/func/test_audio.py
- tests/unit/lib/test_audio.py
Add Audio and AudioFragment support, to make code like below work with full streaming (no file download happening):
```python
from collections.abc import Iterator
import torch
from transformers import Pipeline, pipeline
import datachain as dc
from datachain import AudioFile, AudioFragment
def fragments(file: AudioFile) -> Iterator[AudioFragment]:
yield file.get_fragment(300, 400)
def process(fragment: AudioFragment, pipeline: Pipeline) -> str:
"""Process audio fragment using direct numpy conversion."""
audio_array, sample_rate = fragment.get_np()
if len(audio_array.shape) > 1 and audio_array.shape[1] > 1:
audio_array = audio_array.mean(axis=1)
result = pipeline({
"array": audio_array,
"sampling_rate": sample_rate
})
return str(result)
(
dc
.read_storage("s3://ivan-test-versioned/sounds", …
```
> feat(audio): audio file and fragment with streaming
